/* A scripted run through the editor's real DOM, for a browser to execute.
 *
 * bin/test cannot run this — there is no browser in it — so it is a file you
 * open: tests/editor-probe.html, generated by bin/build from editor/index.html
 * so it can never drift from the page it tests. Every assertion below is a bug
 * the editor once had. A green run means the writing loop still survives
 * adding, removing, clicking away mid-edit, folding, and deleting every line.
 *
 *   $ firefox tests/editor-probe.html      (or open it any other way) */
(function () {
  var out = [];
  function ok(name, cond, got) { out.push((cond ? 'ok   ' : 'FAIL ') + name + (cond ? '' : '  -> ' + got)); }
  function key(k, el, shift, ctrl) {
    (el || document).dispatchEvent(new KeyboardEvent('keydown',
      { key: k, shiftKey: !!shift, ctrlKey: !!ctrl, bubbles: true, cancelable: true }));
  }
  /* type a line into the command line and run it, the way : does */
  function run(text) {
    key(':');
    var input = document.getElementById('cmdInput');
    input.value = text;
    key('Enter', input);
  }
  /* put text in the command line and let it recompute its completions */
  function typeCmd(text) {
    key(':');
    var input = document.getElementById('cmdInput');
    input.value = text;
    input.dispatchEvent(new Event('input', { bubbles: true }));
    return input;
  }
  function msg()  { return document.getElementById('msg').textContent; }
  function name() { return document.getElementById('docname').textContent; }
  /* the tab bar shows the name only; the whole path is in the export overlay */
  function path() {
    run('export');
    var p = document.getElementById('expPath').textContent;
    key('Escape');
    return p;
  }
  function rows() {
    return [].map.call(document.querySelectorAll('#sheet .ln'), function (r) {
      return r.className.replace('ln ', '').replace(' cur', '*') + ':' +
             r.querySelector('.txt').textContent;
    });
  }
  function box() { return document.querySelector('#sheet .ln.cur .txt[contenteditable]'); }
  function type(text) {
    var b = box();
    if (!b) return false;
    b.textContent = text;
    return true;
  }

  /* start clean: one meta + one heading */
  var n0 = rows().length;

  /* --- the writing loop: o, type, Enter, type, Escape ------------------ */
  key('G');
  key('o');
  ok('o opens an edit box', !!box());
  type('first line');
  key('Enter', box());
  ok('Enter commits and opens the next box', !!box(), 'no box');
  type('second line');
  key('Escape', box());
  ok('Escape closes the box', !box());
  var r = rows();
  ok('both lines are in the document',
     r.join('|').indexOf('first line') > -1 && r.join('|').indexOf('second line') > -1, r.join('|'));
  ok('two lines were added', rows().length === n0 + 2, rows().length);

  /* --- remove, then keep editing --------------------------------------- */
  key('D');
  ok('D removed the line', rows().join('|').indexOf('second line') < 0, rows().join('|'));
  key('i');
  ok('i still opens a box after a removal', !!box());
  type('edited after removal');
  key('Escape', box());
  ok('the edit landed on the right line',
     rows().join('|').indexOf('edited after removal') > -1, rows().join('|'));

  /* --- clicking another line while the box is open --------------------- */
  key('i');
  type('mid-edit text');
  var target = document.querySelectorAll('#sheet .ln')[1];
  target.dispatchEvent(new MouseEvent('mousedown', { bubbles: true }));
  target.dispatchEvent(new MouseEvent('click', { bubbles: true }));
  ok('a click while editing moves the cursor',
     document.querySelectorAll('#sheet .ln')[1].classList.contains('cur'),
     document.querySelector('#sheet .ln.cur').dataset.i);
  ok('and the text typed before the click was kept',
     rows().join('|').indexOf('mid-edit text') > -1, rows().join('|'));

  /* --- folded output: the cursor must never vanish into it ------------- */
  key('G');
  var before = rows().length;
  key('u');                        /* make the last line an output line */
  key('o');                        /* add another output line */
  ok('output lines can still be typed into', !!box());
  type('printed');
  key('Escape', box());
  key('z');                        /* fold this output run */
  key('z');                        /* and unfold it */
  key('i');
  ok('i works on a line whose run was just folded and unfolded', !!box());
  key('Escape', box());
  ok('the document did not lose lines to the fold', rows().length === before + 1, rows().length);

  /* --- delete every line ---------------------------------------------- */
  key('g');
  for (var i = 0; i < 60; i++) key('D');
  ok('deleting everything leaves exactly one line', rows().length === 1, rows().length);
  ok('and that line is an empty paragraph', /^p\*?:/.test(rows()[0]), rows()[0]);
  key('i');
  ok('the emptied document is still editable', !!box());
  type('back from empty');
  key('Escape', box());
  ok('and takes text', rows()[0].indexOf('back from empty') > -1, rows()[0]);

  /* --- undo and redo --------------------------------------------------- */
  var kept = rows().join('|');
  key('o');
  type('a line to take back');
  key('Escape', box());
  ok('the line is there to take back', rows().length === 2, rows().length);
  key('z', document, false, true);
  ok('^Z takes the change back', rows().join('|') === kept, rows().join('|'));
  key('z', document, true, true);
  ok('^⇧Z puts it back', rows().length === 2, rows().join('|'));
  key('z', document, false, true);
  ok('and ^Z takes it away again', rows().length === 1, rows().join('|'));
  key('j');
  key('k');
  key('z', document, false, true);
  ok('moving the cursor is not something to undo', rows().length === 1, rows().join('|'));

  /* --- the name of the file -------------------------------------------- */
  run('title Hello There');
  ok('the name follows the title while none is set', name() === 'hello-there.md', name());
  run('cat news');
  var p = path();
  ok('the category is the directory the file goes in', p === 'content/news/hello-there.md', p);
  run('name my-file.md');
  ok('a name that was set wins over the title', name() === 'my-file.md', name());
  run('title Something Else');
  ok('and goes on winning', name() === 'my-file.md', name());
  run('name');
  ok('an empty name follows the title again', name() === 'something-else.md', name());

  /* --- the command line ------------------------------------------------ */
  var n1 = rows().length;
  run('new p');
  ok(': new adds a line', rows().length === n1 + 1, rows().length);
  run('del');
  ok(': del takes it away', rows().length === n1, rows().length);
  run('set h2');
  ok(': set changes the type of the line',
     document.querySelector('#sheet .ln.cur').classList.contains('h2'),
     document.querySelector('#sheet .ln.cur').className);
  run('split');
  ok(': split shows both panes', document.getElementById('panes').dataset.mode === 'split');
  run('swap');
  ok(': swap swaps them, and stays in split',
     document.getElementById('panes').dataset.swap === 'yes' &&
     document.getElementById('panes').dataset.mode === 'split');
  run('swap');
  run('write');
  run('nonsense');
  ok('an unknown command is refused, not run', msg().indexOf('unknown command') === 0, msg());
  ok('every command in the table is documented in the help',
     document.querySelectorAll('#cmdlist .row').length >= 25,
     document.querySelectorAll('#cmdlist .row').length);

  /* --- new, clear, and getting them back ------------------------------- */
  document.getElementById('actNew').click();
  ok('New .md starts a document with its metadata and a heading',
     rows().length === 4, rows().join('|'));
  p = path();
  ok('and keeps the category it was filed under', p === 'content/news/untitled.md', p);
  ok('and goes back to being called untitled', name() === 'untitled.md', name());
  document.getElementById('actClear').click();
  ok('Clear leaves one empty line', rows().length === 1, rows().join('|'));
  key('z', document, false, true);
  ok('and ^Z brings the whole document back', rows().length === 4, rows().join('|'));

  /* --- Tab completes arguments, and leaves alone what it cannot complete -- */
  var input = typeCmd('title My Great Post');
  key('Tab', input);
  ok('Tab leaves an argument it has no completions for',
     input.value === 'title My Great Post', input.value);
  key('Escape', input);

  input = typeCmd('set code p');
  key('Tab', input);
  ok('Tab completes a dialect for the second argument of set',
     input.value === 'set code php ', input.value);
  key('Escape', input);

  input = typeCmd('se');
  key('Tab', input);
  ok('and completes a command name for the first word', input.value === 'set ', input.value);
  key('Escape', input);

  /* --- folding is looking, not editing ---------------------------------- */
  key('G');
  key('u');                        /* the last line becomes output */
  key('o');
  type('printed');
  key('Escape', box());
  var withPrinted = rows().length;
  key('z');                        /* fold the run */
  key('z');                        /* and unfold it — the same view again */
  key('z', document, false, true);
  ok('folding is not a step to undo — ^Z takes back the text instead',
     rows().length === withPrinted - 1, rows().length + ' of ' + withPrinted);

  /* --- the address overlay: the links in a line, and an image's two halves -- */
  function addrOn()  { return document.getElementById('addr').classList.contains('on'); }
  function picking() { return addrOn() && !document.getElementById('addrPick').hidden; }
  function fa()      { return document.getElementById('addrA'); }
  function fb()      { return document.getElementById('addrB'); }
  function warn()    { return document.getElementById('addrWarn').textContent; }
  /* a fresh document holding one line of the given text */
  function oneLine(text) {
    document.getElementById('actClear').click();
    key('i');
    type(text);
    key('Escape', box());
  }

  oneLine('see [one](https://a.example/) and [two](https://b.example/)');
  key('a');
  ok('a on a line with two links opens the picker', picking());
  ok('the picker offers both links and a new one',
     document.querySelectorAll('#addrPick b').length === 3,
     document.querySelectorAll('#addrPick b').length);
  key('2');
  ok('picking the second fills the form with the second link',
     fa().value === 'two' && fb().value === 'https://b.example/',
     fa().value + ' / ' + fb().value);
  key('Escape', fa());
  key('a');
  key('j');
  key('Enter');
  ok('j and Enter reach the same link the digit does',
     !picking() && fa().value === 'two' && fb().value === 'https://b.example/',
     fa().value + ' / ' + fb().value);
  key('Escape', fa());
  key('a');
  key('j');
  key('k');
  key('Enter');
  ok('k comes back up the list', fa().value === 'one', fa().value);
  key('Escape', fa());
  key('a');
  key('2');
  fa().focus();
  key('Tab', fa());
  ok('Tab moves to the other field', document.activeElement === fb(),
     document.activeElement && document.activeElement.id);
  fa().value = 'TWO';
  fb().value = 'https://c.example/';
  key('Enter', fb());
  ok('Enter commits and closes the overlay', !addrOn());
  ok('and the line carries the link that was typed',
     rows().join('|').indexOf('see [one](https://a.example/) and [TWO](https://c.example/)') > -1,
     rows().join('|'));

  var kept2 = rows().join('|');
  key('a');
  key('1');
  fa().value = 'thrown away';
  key('Escape', fa());
  ok('Esc leaves the line exactly as it was',
     !addrOn() && rows().join('|') === kept2, rows().join('|'));

  run('link');
  ok(': link opens the same overlay as a', addrOn());
  key('Escape', fa());
  run('img');
  ok(': img opens it too', addrOn());
  key('Escape', fa());

  oneLine('one [only](https://a.example/) here');
  key('a');
  ok('one link goes straight to a filled form',
     addrOn() && !picking() && fa().value === 'only', fa().value);
  key('Escape', fa());

  oneLine('no links here');
  key('a');
  ok('no links goes straight to an empty form',
     addrOn() && !picking() && !fa().value && !fb().value, fa().value + ' / ' + fb().value);
  fa().value = 'fresh';
  fb().value = 'https://d.example/';
  key('Enter', fa());
  ok('a new link is appended to the line',
     rows().join('|').indexOf('no links here [fresh](https://d.example/)') > -1, rows().join('|'));

  key('a');
  fb().value = '';
  key('Enter', fa());
  ok('an empty href unlinks and keeps the wording',
     rows().join('|').indexOf('no links here fresh') > -1 &&
     rows().join('|').indexOf('[fresh]') < 0, rows().join('|'));

  oneLine('a [word](https://a.example/) here');
  var before2 = rows().join('|');
  key('a');
  fa().value = '';
  key('Enter', fa());
  ok('an empty wording is refused, with a message and no change',
     addrOn() && msg().indexOf('wording') > -1 && rows().join('|') === before2,
     msg() + ' :: ' + rows().join('|'));

  fa().value = 'word';
  fb().value = 'javascript:alert';
  fb().dispatchEvent(new Event('input', { bubbles: true }));
  ok('an href the allowlist refuses is marked in the overlay',
     warn().indexOf('print as text') > -1, warn());
  key('Enter', fb());
  ok('and Enter commits it anyway',
     !addrOn() && rows().join('|').indexOf('[word](javascript:alert)') > -1, rows().join('|'));

  key('z', document, false, true);
  ok('one committed overlay is one ^Z',
     rows().join('|') === before2, rows().join('|'));

  document.getElementById('actClear').click();
  key('c');
  var kept3 = rows().join('|');
  key('a');
  ok('a on a code line says so and changes nothing',
     !addrOn() && msg().indexOf('nothing to address') > -1 && rows().join('|') === kept3,
     msg() + ' :: ' + rows().join('|'));

  document.getElementById('actClear').click();
  key('f');
  key('a');
  ok('a on an image line offers src and caption',
     addrOn() && document.getElementById('addrLab1').textContent === 'src' &&
     document.getElementById('addrLab2').textContent === 'caption',
     document.getElementById('addrLab1').textContent);
  fa().value = 'diagram.png';
  fb().value = 'how it fits together';
  key('Enter', fb());
  run('export');
  var md = document.getElementById('expMd').textContent;
  key('Escape');
  ok('a committed caption reaches the export',
     md.indexOf('![how it fits together](diagram.png)') > -1, md);
  var fig = document.querySelector('#read figure');
  ok('and the read pane shows the picture itself',
     !!document.querySelector('#read figure img[src="diagram.png"]'),
     fig && fig.innerHTML);
  ok('with the box holding the file name behind it, for an src that will not load',
     !!fig && !!fig.querySelector('.imgbox[hidden]') &&
     fig.querySelector('.imgbox').textContent === 'diagram.png',
     fig && fig.innerHTML);
  ok('and the caption is the alt as well as the figcaption',
     !!fig && fig.querySelector('img').alt === 'how it fits together' &&
     fig.querySelector('figcaption').textContent === 'how it fits together',
     fig && fig.innerHTML);

  oneLine('[kept  wording](https://a.example/)');
  key('a');
  fb().value = '';
  key('Enter', fa());
  ok('unlinking keeps the wording the field shows',
     rows().join('|').indexOf('kept  wording') > -1 &&
     rows().join('|').indexOf('[') < 0, rows().join('|'));

  oneLine('[old](https://a.example/)');
  key('a');
  fa().value = 'new wording';
  fb().value = '';
  key('Enter', fa());
  ok('and a wording edited on the way out is not thrown away',
     rows().join('|').indexOf('new wording') > -1, rows().join('|'));

  var bad = out.filter(function (l) { return l.indexOf('FAIL') === 0; }).length;
  var pre = document.createElement('pre');
  pre.style.cssText = 'position:fixed;inset:0;z-index:999;background:#111;color:#ddd;' +
    'font:12px/1.5 monospace;padding:14px;margin:0;overflow:auto;white-space:pre-wrap';
  pre.textContent = out.join('\n') + '\n\n' + bad + ' failed of ' + out.length;
  document.body.appendChild(pre);
})();
