/* A scripted run through the editor's real DOM, for a browser to execute.
 *
 * bin/test cannot run this — there is no browser in it — so it is a file you
 * open: tests/editor-probe.html, generated by bin/build from editor/index.html
 * so it can never drift from the page it tests. Every assertion below is a bug
 * the editor once had. A green run means the writing loop still survives
 * adding, removing, clicking away mid-edit, folding, and deleting every line.
 *
 *   $ firefox tests/editor-probe.html      (or open it any other way) */
(function () {
  var out = [];
  function ok(name, cond, got) { out.push((cond ? 'ok   ' : 'FAIL ') + name + (cond ? '' : '  -> ' + got)); }
  function key(k, el, shift, ctrl) {
    (el || document).dispatchEvent(new KeyboardEvent('keydown',
      { key: k, shiftKey: !!shift, ctrlKey: !!ctrl, bubbles: true, cancelable: true }));
  }
  /* type a line into the command line and run it, the way : does */
  function run(text) {
    key(':');
    var input = document.getElementById('cmdInput');
    input.value = text;
    key('Enter', input);
  }
  /* put text in the command line and let it recompute its completions */
  function typeCmd(text) {
    key(':');
    var input = document.getElementById('cmdInput');
    input.value = text;
    input.dispatchEvent(new Event('input', { bubbles: true }));
    return input;
  }
  function msg()  { return document.getElementById('msg').textContent; }
  function name() { return document.getElementById('docname').textContent; }
  /* the tab bar shows the name only; the whole path is in the export overlay */
  function path() {
    run('export');
    var p = document.getElementById('expPath').textContent;
    key('Escape');
    return p;
  }
  function rows() {
    return [].map.call(document.querySelectorAll('#sheet .ln'), function (r) {
      return r.className.replace('ln ', '').replace(' cur', '*') + ':' +
             r.querySelector('.txt').textContent;
    });
  }
  function box() { return document.querySelector('#sheet .ln.cur .txt[contenteditable]'); }
  function type(text) {
    var b = box();
    if (!b) return false;
    b.textContent = text;
    return true;
  }

  /* start clean: one meta + one heading */
  var n0 = rows().length;

  /* --- the writing loop: o, type, Enter, type, Escape ------------------ */
  key('G');
  key('o');
  ok('o opens an edit box', !!box());
  type('first line');
  key('Enter', box());
  ok('Enter commits and opens the next box', !!box(), 'no box');
  type('second line');
  key('Escape', box());
  ok('Escape closes the box', !box());
  var r = rows();
  ok('both lines are in the document',
     r.join('|').indexOf('first line') > -1 && r.join('|').indexOf('second line') > -1, r.join('|'));
  ok('two lines were added', rows().length === n0 + 2, rows().length);

  /* --- remove, then keep editing --------------------------------------- */
  key('D');
  ok('D removed the line', rows().join('|').indexOf('second line') < 0, rows().join('|'));
  key('i');
  ok('i still opens a box after a removal', !!box());
  type('edited after removal');
  key('Escape', box());
  ok('the edit landed on the right line',
     rows().join('|').indexOf('edited after removal') > -1, rows().join('|'));

  /* --- clicking another line while the box is open --------------------- */
  key('i');
  type('mid-edit text');
  var target = document.querySelectorAll('#sheet .ln')[1];
  target.dispatchEvent(new MouseEvent('mousedown', { bubbles: true }));
  target.dispatchEvent(new MouseEvent('click', { bubbles: true }));
  ok('a click while editing moves the cursor',
     document.querySelectorAll('#sheet .ln')[1].classList.contains('cur'),
     document.querySelector('#sheet .ln.cur').dataset.i);
  ok('and the text typed before the click was kept',
     rows().join('|').indexOf('mid-edit text') > -1, rows().join('|'));

  /* --- folded output: the cursor must never vanish into it ------------- */
  key('G');
  var before = rows().length;
  key('u');                        /* make the last line an output line */
  key('o');                        /* add another output line */
  ok('output lines can still be typed into', !!box());
  type('printed');
  key('Escape', box());
  key('z');                        /* fold this output run */
  key('z');                        /* and unfold it */
  key('i');
  ok('i works on a line whose run was just folded and unfolded', !!box());
  key('Escape', box());
  ok('the document did not lose lines to the fold', rows().length === before + 1, rows().length);

  /* --- delete every line ---------------------------------------------- */
  key('g');
  for (var i = 0; i < 60; i++) key('D');
  ok('deleting everything leaves exactly one line', rows().length === 1, rows().length);
  ok('and that line is an empty paragraph', /^p\*?:/.test(rows()[0]), rows()[0]);
  key('i');
  ok('the emptied document is still editable', !!box());
  type('back from empty');
  key('Escape', box());
  ok('and takes text', rows()[0].indexOf('back from empty') > -1, rows()[0]);

  /* --- undo and redo --------------------------------------------------- */
  var kept = rows().join('|');
  key('o');
  type('a line to take back');
  key('Escape', box());
  ok('the line is there to take back', rows().length === 2, rows().length);
  key('z', document, false, true);
  ok('^Z takes the change back', rows().join('|') === kept, rows().join('|'));
  key('z', document, true, true);
  ok('^⇧Z puts it back', rows().length === 2, rows().join('|'));
  key('z', document, false, true);
  ok('and ^Z takes it away again', rows().length === 1, rows().join('|'));
  key('j');
  key('k');
  key('z', document, false, true);
  ok('moving the cursor is not something to undo', rows().length === 1, rows().join('|'));

  /* --- the name of the file -------------------------------------------- */
  run('title Hello There');
  ok('the name follows the title while none is set', name() === 'hello-there.md', name());
  run('cat news');
  var p = path();
  ok('the category is the directory the file goes in', p === 'content/news/hello-there.md', p);
  run('name my-file.md');
  ok('a name that was set wins over the title', name() === 'my-file.md', name());
  run('title Something Else');
  ok('and goes on winning', name() === 'my-file.md', name());
  run('name');
  ok('an empty name follows the title again', name() === 'something-else.md', name());

  /* --- the command line ------------------------------------------------ */
  var n1 = rows().length;
  run('new p');
  ok(': new adds a line', rows().length === n1 + 1, rows().length);
  run('del');
  ok(': del takes it away', rows().length === n1, rows().length);
  run('set h2');
  ok(': set changes the type of the line',
     document.querySelector('#sheet .ln.cur').classList.contains('h2'),
     document.querySelector('#sheet .ln.cur').className);
  run('split');
  ok(': split shows both panes', document.getElementById('panes').dataset.mode === 'split');
  run('swap');
  ok(': swap swaps them, and stays in split',
     document.getElementById('panes').dataset.swap === 'yes' &&
     document.getElementById('panes').dataset.mode === 'split');
  run('swap');
  run('write');
  run('nonsense');
  ok('an unknown command is refused, not run', msg().indexOf('unknown command') === 0, msg());
  ok('every command in the table is documented in the help',
     document.querySelectorAll('#cmdlist .row').length >= 25,
     document.querySelectorAll('#cmdlist .row').length);

  /* --- new, clear, and getting them back ------------------------------- */
  document.getElementById('actNew').click();
  ok('New .md starts a document with its metadata and a heading',
     rows().length === 4, rows().join('|'));
  p = path();
  ok('and keeps the category it was filed under', p === 'content/news/untitled.md', p);
  ok('and goes back to being called untitled', name() === 'untitled.md', name());
  document.getElementById('actClear').click();
  ok('Clear leaves one empty line', rows().length === 1, rows().join('|'));
  key('z', document, false, true);
  ok('and ^Z brings the whole document back', rows().length === 4, rows().join('|'));

  /* --- Tab completes arguments, and leaves alone what it cannot complete -- */
  var input = typeCmd('title My Great Post');
  key('Tab', input);
  ok('Tab leaves an argument it has no completions for',
     input.value === 'title My Great Post', input.value);
  key('Escape', input);

  input = typeCmd('set code p');
  key('Tab', input);
  ok('Tab completes a dialect for the second argument of set',
     input.value === 'set code php ', input.value);
  key('Escape', input);

  input = typeCmd('se');
  key('Tab', input);
  ok('and completes a command name for the first word', input.value === 'set ', input.value);
  key('Escape', input);

  /* --- folding is looking, not editing ---------------------------------- */
  key('G');
  key('u');                        /* the last line becomes output */
  key('o');
  type('printed');
  key('Escape', box());
  var withPrinted = rows().length;
  key('z');                        /* fold the run */
  key('z');                        /* and unfold it — the same view again */
  key('z', document, false, true);
  ok('folding is not a step to undo — ^Z takes back the text instead',
     rows().length === withPrinted - 1, rows().length + ' of ' + withPrinted);

  var bad = out.filter(function (l) { return l.indexOf('FAIL') === 0; }).length;
  var pre = document.createElement('pre');
  pre.style.cssText = 'position:fixed;inset:0;z-index:999;background:#111;color:#ddd;' +
    'font:12px/1.5 monospace;padding:14px;margin:0;overflow:auto;white-space:pre-wrap';
  pre.textContent = out.join('\n') + '\n\n' + bad + ' failed of ' + out.length;
  document.body.appendChild(pre);
})();
