/* A scripted run through the editor's real DOM, for a browser to execute.
 *
 * bin/test cannot run this — there is no browser in it — so it is a file you
 * open: tests/editor-probe.html, generated by bin/build from editor/index.html
 * so it can never drift from the page it tests. Every assertion below is a bug
 * the editor once had. A green run means the writing loop still survives
 * adding, removing, clicking away mid-edit, folding, and deleting every line.
 *
 *   $ firefox tests/editor-probe.html      (or open it any other way) */
(function () {
  var out = [];
  /* what the Editor made of the kept Palette as it loaded, before any key */
  var paletteAtLoad = document.documentElement.getAttribute('data-palette');
  var paletteKept = paletteStored();
  function paletteStored() {
    try { return localStorage.getItem('tcms-palette'); } catch (e) { return 'unreadable'; }
  }
  /* and of the kept Theme */
  var themeAtLoad = document.documentElement.getAttribute('data-theme');
  var themeKept = themeStored();
  function themeStored() {
    try { return localStorage.getItem('tcms-theme'); } catch (e) { return 'unreadable'; }
  }
  var THEME_NAMES = (window.THEMES || []).map(function (t) { return t.name; });
  function ok(name, cond, got) { out.push((cond ? 'ok   ' : 'FAIL ') + name + (cond ? '' : '  -> ' + got)); }
  function key(k, el, shift, ctrl) {
    (el || document).dispatchEvent(new KeyboardEvent('keydown',
      { key: k, shiftKey: !!shift, ctrlKey: !!ctrl, bubbles: true, cancelable: true }));
  }
  /* type a line into the command line and run it, the way : does */
  function run(text) {
    key(':');
    var input = document.getElementById('cmdInput');
    input.value = text;
    key('Enter', input);
  }
  /* put text in the command line and let it recompute its completions */
  function typeCmd(text) {
    key(':');
    var input = document.getElementById('cmdInput');
    input.value = text;
    input.dispatchEvent(new Event('input', { bubbles: true }));
    return input;
  }
  function msg()  { return document.getElementById('msg').textContent; }
  function name() { return document.getElementById('docname').textContent; }
  /* the tab bar shows the name only; the whole path is in the export overlay */
  function path() {
    run('export');
    var p = document.getElementById('expPath').textContent;
    key('Escape');
    return p;
  }
  /* what E shows: toMarkdown of the Document */
  function exported() {
    run('export');
    var t = document.getElementById('expMd').textContent;
    key('Escape');
    return t;
  }
  function rows() {
    return [].map.call(document.querySelectorAll('#sheet .ln'), function (r) {
      return r.className.replace('ln ', '').replace(' cur', '*') + ':' +
             r.querySelector('.txt').textContent;
    });
  }
  function box() { return document.querySelector('#sheet .ln.cur .txt[contenteditable]'); }
  function type(text) {
    var b = box();
    if (!b) return false;
    b.textContent = text;
    return true;
  }

  /* the Document the Editor opens with is the starter the page carries */
  var starter = document.getElementById('starter').textContent;
  var opened = exported();
  ok('the Editor opens with the starter document',
     /# Start typing/.test(starter) &&
     opened === window.TerminalCms.toMarkdown(window.TerminalCms.parse(starter)),
     opened.slice(0, 120));

  /* start clean: one meta + one heading */
  var n0 = rows().length;

  /* --- the writing loop: o, type, Enter, type, Escape ------------------ */
  key('G');
  key('o');
  ok('o opens an edit box', !!box());
  type('first line');
  key('Enter', box());
  ok('Enter commits and opens the next box', !!box(), 'no box');
  type('second line');
  key('Escape', box());
  ok('Escape closes the box', !box());
  var r = rows();
  ok('both lines are in the document',
     r.join('|').indexOf('first line') > -1 && r.join('|').indexOf('second line') > -1, r.join('|'));
  ok('two lines were added', rows().length === n0 + 2, rows().length);

  /* --- remove, then keep editing --------------------------------------- */
  key('D');
  ok('D removed the line', rows().join('|').indexOf('second line') < 0, rows().join('|'));
  key('i');
  ok('i still opens a box after a removal', !!box());
  type('edited after removal');
  key('Escape', box());
  ok('the edit landed on the right line',
     rows().join('|').indexOf('edited after removal') > -1, rows().join('|'));

  /* --- clicking another line while the box is open --------------------- */
  key('i');
  type('mid-edit text');
  var target = document.querySelectorAll('#sheet .ln')[1];
  target.dispatchEvent(new MouseEvent('mousedown', { bubbles: true }));
  target.dispatchEvent(new MouseEvent('click', { bubbles: true }));
  ok('a click while editing moves the cursor',
     document.querySelectorAll('#sheet .ln')[1].classList.contains('cur'),
     document.querySelector('#sheet .ln.cur').dataset.i);
  ok('and the text typed before the click was kept',
     rows().join('|').indexOf('mid-edit text') > -1, rows().join('|'));

  /* --- folded output: the cursor must never vanish into it ------------- */
  key('G');
  var before = rows().length;
  key('u');                        /* make the last line an output line */
  key('o');                        /* add another output line */
  ok('output lines can still be typed into', !!box());
  type('printed');
  key('Escape', box());
  key('z');                        /* fold this output run */
  key('z');                        /* and unfold it */
  key('i');
  ok('i works on a line whose run was just folded and unfolded', !!box());
  key('Escape', box());
  ok('the document did not lose lines to the fold', rows().length === before + 1, rows().length);

  /* --- delete every line ---------------------------------------------- */
  key('g');
  for (var i = 0; i < 60; i++) key('D');
  ok('deleting everything leaves exactly one line', rows().length === 1, rows().length);
  ok('and that line is an empty paragraph', /^p\*?:/.test(rows()[0]), rows()[0]);
  key('i');
  ok('the emptied document is still editable', !!box());
  type('back from empty');
  key('Escape', box());
  ok('and takes text', rows()[0].indexOf('back from empty') > -1, rows()[0]);

  /* --- undo and redo --------------------------------------------------- */
  var kept = rows().join('|');
  key('o');
  type('a line to take back');
  key('Escape', box());
  ok('the line is there to take back', rows().length === 2, rows().length);
  key('z', document, false, true);
  ok('^Z takes the change back', rows().join('|') === kept, rows().join('|'));
  key('z', document, true, true);
  ok('^⇧Z puts it back', rows().length === 2, rows().join('|'));
  key('z', document, false, true);
  ok('and ^Z takes it away again', rows().length === 1, rows().join('|'));
  key('j');
  key('k');
  key('z', document, false, true);
  ok('moving the cursor is not something to undo', rows().length === 1, rows().join('|'));

  /* --- the name of the file -------------------------------------------- */
  run('title Hello There');
  ok('the name follows the title while none is set', name() === 'hello-there.md', name());
  run('cat news');
  var p = path();
  ok('the category is the directory the file goes in', p === 'content/news/hello-there.md', p);
  run('name my-file.md');
  ok('a name that was set wins over the title', name() === 'my-file.md', name());
  run('title Something Else');
  ok('and goes on winning', name() === 'my-file.md', name());
  run('name');
  ok('an empty name follows the title again', name() === 'something-else.md', name());

  /* --- the command line ------------------------------------------------ */
  var n1 = rows().length;
  run('new p');
  ok(': new adds a line', rows().length === n1 + 1, rows().length);
  run('del');
  ok(': del takes it away', rows().length === n1, rows().length);
  run('set h2');
  ok(': set changes the type of the line',
     document.querySelector('#sheet .ln.cur').classList.contains('h2'),
     document.querySelector('#sheet .ln.cur').className);
  run('split');
  ok(': split shows both panes', document.getElementById('panes').dataset.mode === 'split');
  run('swap');
  ok(': swap swaps them, and stays in split',
     document.getElementById('panes').dataset.swap === 'yes' &&
     document.getElementById('panes').dataset.mode === 'split');
  run('swap');
  run('write');
  run('nonsense');
  ok('an unknown command is refused, not run', msg().indexOf('unknown command') === 0, msg());
  ok('every command in the table is documented in the help',
     document.querySelectorAll('#cmdlist .row').length >= 25,
     document.querySelectorAll('#cmdlist .row').length);

  /* --- new, clear, and getting them back ------------------------------- */
  document.getElementById('actNew').click();
  ok('New .md starts a document with its metadata and a heading',
     rows().length === 4, rows().join('|'));
  p = path();
  ok('and keeps the category it was filed under', p === 'content/news/untitled.md', p);
  ok('and goes back to being called untitled', name() === 'untitled.md', name());
  document.getElementById('actClear').click();
  ok('Clear leaves one empty line', rows().length === 1, rows().join('|'));
  key('z', document, false, true);
  ok('and ^Z brings the whole document back', rows().length === 4, rows().join('|'));

  /* --- Tab completes arguments, and leaves alone what it cannot complete -- */
  var input = typeCmd('title My Great Post');
  key('Tab', input);
  ok('Tab leaves an argument it has no completions for',
     input.value === 'title My Great Post', input.value);
  key('Escape', input);

  input = typeCmd('set code p');
  key('Tab', input);
  ok('Tab completes a dialect for the second argument of set',
     input.value === 'set code php ', input.value);
  key('Escape', input);

  input = typeCmd('se');
  key('Tab', input);
  ok('and completes a command name for the first word', input.value === 'set ', input.value);
  key('Escape', input);

  /* --- folding is looking, not editing ---------------------------------- */
  key('G');
  key('u');                        /* the last line becomes output */
  key('o');
  type('printed');
  key('Escape', box());
  var withPrinted = rows().length;
  key('z');                        /* fold the run */
  key('z');                        /* and unfold it — the same view again */
  key('z', document, false, true);
  ok('folding is not a step to undo — ^Z takes back the text instead',
     rows().length === withPrinted - 1, rows().length + ' of ' + withPrinted);

  /* --- tables: a row the width of its Run, and Tab between its Cells ---- */
  function cellsIn(b) { return window.TerminalCms.cells(b.textContent); }
  /* the caret in the open box, counted in characters, read and written */
  function caret() {
    var b = box(), s = getSelection(), r = document.createRange();
    if (!b || !s.rangeCount) return -1;
    r.selectNodeContents(b);
    r.setEnd(s.getRangeAt(0).endContainer, s.getRangeAt(0).endOffset);
    return r.toString().length;
  }
  function putCaret(at) {
    var b = box(), r = document.createRange();
    if (b.firstChild) r.setStart(b.firstChild, at); else r.selectNodeContents(b);
    r.collapse(true);
    var s = getSelection();
    s.removeAllRanges();
    s.addRange(r);
  }

  document.getElementById('actClear').click();
  key('t');                          /* the one line becomes a Table Line */
  key('i');
  type('one | two | three');
  key('Escape', box());
  key('o');
  ok('o on a Line of a three-Column Run opens a three-Cell row',
     !!box() && cellsIn(box()).length === 3, box() && box().textContent);

  type('a | b | c');
  putCaret(0);
  key('Tab', box());
  ok('Tab moves the caret to the next Cell',
     caret() === box().textContent.indexOf('b') + 1, caret());
  key('Tab', box());
  ok('and on to the Cell after that',
     caret() === box().textContent.indexOf('c') + 1, caret());
  var nt = rows().length;
  key('Tab', box());
  ok('Tab on the last Cell opens the next row', rows().length === nt + 1, rows().length);
  ok('with the caret in its first Cell', !!box() && caret() === 0, caret());
  ok('and that row is the width of the Run too',
     cellsIn(box()).length === 3, box().textContent);
  ok('the row Tab left behind was committed',
     rows().join('|').indexOf('a | b | c') > -1, rows().join('|'));
  key('Tab', box(), true);
  ok('Shift-Tab on the first Cell does nothing',
     !!box() && caret() === 0 && rows().length === nt + 1, caret() + ' of ' + rows().length);
  key('Escape', box());

  document.getElementById('actClear').click();
  key('t');
  key('i');
  type('x | y');
  key('Enter', box());
  ok('Enter while editing a Table Line still commits and opens the next Line',
     !!box() && rows().join('|').indexOf('x | y') > -1, rows().join('|'));
  key('Escape', box());

  /* the bug the probe first missed: Tab out of the very first row of a table,
     whose text was still only in the box when the next row was sized */
  document.getElementById('actClear').click();
  key('t');
  key('i');
  type('p | q | r');
  putCaret(box().textContent.length);
  key('Tab', box());
  ok('Tab out of the first row of a new table commits it before measuring it',
     !!box() && cellsIn(box()).length === 3, box() && box().textContent);
  ok('and the row it came from is in the document',
     rows().join('|').indexOf('p | q | r') > -1, rows().join('|'));
  key('Escape', box());

  /* --- columns: one command, every Line of the Run ---------------------- */
  function tableRows() {
    return rows().filter(function (r) { return r.indexOf('table') === 0; })
                 .map(function (r) { return r.slice(r.indexOf(':') + 1); });
  }
  function compls() {
    return [].map.call(document.querySelectorAll('#compl b'), function (b) {
      return b.textContent;
    });
  }

  document.getElementById('actClear').click();
  key('t');
  key('i');
  type('one | two | three');
  key('Escape', box());
  key('o');
  type('a | b | c');
  key('Escape', box());
  var before = tableRows().join(' / ');
  ok('the table the column commands work on is two rows of three',
     before === 'one | two | three / a | b | c', before);

  run('col add');
  ok(':col add puts an empty Column on the right of every Line',
     tableRows().join(' / ') === 'one | two | three |  / a | b | c | ',
     tableRows().join(' / '));
  key('z', document, false, true);
  ok('and one :col is one ^Z', tableRows().join(' / ') === before, tableRows().join(' / '));

  run('col del 2');
  ok(':col del takes that Column out of every Line',
     tableRows().join(' / ') === 'one | three / a | c', tableRows().join(' / '));

  run('col left 2');
  ok(':col left swaps it with the Column before it, in every Line',
     tableRows().join(' / ') === 'three | one / c | a', tableRows().join(' / '));

  run('col del 99');
  ok(':col del on a Column the table has not got is refused',
     msg().indexOf('no column 99') === 0, msg());
  ok('and the table is exactly as it was',
     tableRows().join(' / ') === 'three | one / c | a', tableRows().join(' / '));

  input = typeCmd('col del ');
  ok('Tab completion on :col del offers the headings against their numbers',
     compls().join(',') === '1 three,2 one', compls().join(','));
  key('Tab', input);
  ok('and picking one writes its number into the command',
     input.value.indexOf('col del 1 three') === 0, input.value);
  key('Escape', input);

  /* --- the strip: a Table that says what its Columns are ---------------- */
  /* one entry per Column, each its number and its heading Cell, and a `*` on
     the one that is selected */
  function strip() {
    return [].map.call(document.querySelectorAll('#sheet .colstrip b'), function (b) {
      return b.textContent + (b.classList.contains('on') ? '*' : '');
    }).join(' / ');
  }
  /* the drawn Cells of the nth Table row on the sheet */
  function cellsOf(n) {
    var r = document.querySelectorAll('#sheet .ln.table')[n];
    return r ? r.querySelectorAll('.cell') : [];
  }

  document.getElementById('actClear').click();
  key('t');
  key('i');
  type('one | two | three');
  key('Escape', box());
  key('o');
  type('a | b | c');
  key('Escape', box());
  ok('a Table Run draws one strip entry per Column, carrying the heading row',
     strip() === '1one / 2two / 3three', strip());

  document.getElementById('actClear').click();
  key('t');
  key('i');
  type('one | two');
  key('Escape', box());
  key('o');
  type('a | b | c');
  key('Escape', box());
  ok('a ragged Run draws the entries its widest row asks for',
     strip() === '1one / 2two / 3', strip());
  ok('and drawing the strip changed no Line',
     tableRows().join(' / ') === 'one | two / a | b | c', tableRows().join(' / '));

  document.getElementById('actClear').click();
  ok('a document with no Table draws no strip', strip() === '', strip());

  /* two Runs, a Paragraph between them, so the bounds have something to stop at */
  document.getElementById('actClear').click();
  key('t');
  key('i');
  type('a1 | a2');
  key('Escape', box());
  key('o');
  key('Escape', box());
  key('p');
  key('i');
  type('between');
  key('Escape', box());
  key('o');
  key('Escape', box());
  key('t');
  key('i');
  type('b1 | b2 | b3');
  key('Escape', box());
  ok('with two Tables the strip is the Run the cursor is in',
     strip() === '1b1 / 2b2 / 3b3', strip());
  key('k');
  ok('a cursor out of the Run draws no strip', strip() === '', strip());
  key('k');
  ok('and in the Run above, the strip is that Run and its Column count',
     strip() === '1a1 / 2a2', strip());

  document.querySelectorAll('#sheet .colstrip b')[1].click();
  ok('clicking an entry selects that Column, visibly',
     strip() === '1a1 / 2a2*', strip());
  key('j');
  ok('the cursor leaving the Run clears the selection with the strip',
     strip() === '', strip());
  key('k');
  ok('and coming back in, nothing is selected', strip() === '1a1 / 2a2', strip());

  document.querySelectorAll('#sheet .colstrip b')[1].click();
  key('G');
  ok('the selection does not travel to the other Run',
     strip() === '1b1 / 2b2 / 3b3', strip());

  /* the selection is the Run's, not the Line's: walking the Run keeps it, and
     it is anchored on a Line object, so an edit above cannot re-point it */
  document.getElementById('actClear').click();
  key('t');
  key('i');
  type('one | two | three');
  key('Escape', box());
  key('o');
  type('a | b | c');
  key('Escape', box());
  document.querySelectorAll('#sheet .colstrip b')[2].click();
  key('k');
  ok('moving within the Run keeps the Column selected',
     strip() === '1one / 2two / 3three*', strip());
  run('col del 3');
  ok('and a Column that is no longer there is no longer selected',
     strip() === '1one / 2two', strip());

  /* --- a Cell is a place to click: the row, and the caret inside it ----- */
  document.getElementById('actClear').click();
  key('t');
  key('i');
  type('a | b | c');
  key('Escape', box());
  ok('a Table row draws one span per Cell', cellsOf(0).length === 3, cellsOf(0).length);

  cellsOf(0)[0].click();
  ok('clicking the first Cell opens the row with the caret in that Cell',
     !!box() && caret() === 1, caret());
  key('Escape', box());
  cellsOf(0)[2].click();
  ok('and clicking the last Cell lands in the last Cell',
     !!box() && caret() === 9, caret());
  key('Escape', box());

  key('o');
  type('d | e | f');
  key('Escape', box());
  cellsOf(0)[1].click();
  ok('clicking a Cell of another row puts the cursor on that row',
     !!box() && box().textContent === 'a | b | c', box() && box().textContent);
  ok('with the caret in the Cell that was clicked', caret() === 5, caret());
  key('Escape', box());
  ok('and the rows are as they were typed',
     tableRows().join(' / ') === 'a | b | c / d | e | f', tableRows().join(' / '));

  /* a tap is a click with a finger behind it: a Cell names a place, so one tap
     is the way in, where a Line still takes the second */
  document.dispatchEvent(new PointerEvent('pointerdown',
    { pointerType: 'touch', bubbles: true }));
  cellsOf(1)[0].click();
  ok('a tap on a Cell opens it the same way a click does',
     !!box() && box().textContent === 'd | e | f' && caret() === 1,
     (box() && box().textContent) + ' @ ' + caret());
  key('Escape', box());
  document.dispatchEvent(new PointerEvent('pointerdown',
    { pointerType: 'mouse', bubbles: true }));

  document.querySelectorAll('#sheet .colstrip b')[0].click();
  var readTbl = document.querySelector('#read table');
  ok('the read pane still renders the Table, and nothing of the strip',
     !!readTbl && readTbl.textContent.replace(/\s+/g, '') === 'abcdef' &&
     document.querySelectorAll('#read .colstrip, #read .cell').length === 0,
     (readTbl && readTbl.textContent.replace(/\s+/g, '')) + ' :: ' +
     document.querySelectorAll('#read .colstrip, #read .cell').length);
  var stripMd = exported();
  ok('and export is the table it always was',
     stripMd.indexOf('| a | b | c |\n| --- | --- | --- |\n| d | e | f |') > -1 &&
     stripMd.indexOf('colstrip') < 0, stripMd);

  /* --- the strip's four: every :col operation with a place to be clicked --- */
  /* the strip draws its four only while a Column is selected, and each one is
     the command it is named after, on the Column that is drawn as chosen */
  function ops() {
    return [].map.call(document.querySelectorAll('#sheet .colstrip button'),
      function (b) { return b.dataset.op; }).join(' ');
  }
  function pick(n) { document.querySelectorAll('#sheet .colstrip b')[n - 1].click(); }
  function op(o) { document.querySelector('#sheet .colstrip button[data-op="' + o + '"]').click(); }
  /* two rows of three, the cursor on the second */
  function table3() {
    document.getElementById('actClear').click();
    key('t');
    key('i');
    type('one | two | three');
    key('Escape', box());
    key('o');
    type('a | b | c');
    key('Escape', box());
  }

  table3();
  ok('an unselected strip offers no operations', ops() === '', ops());
  pick(2);
  ok('a selected Column reveals the four', ops() === 'add del left right', ops());

  var kept = tableRows().join(' / ');
  op('add');
  ok('add from the strip puts an empty Cell in every Line, at that Column',
     tableRows().join(' / ') === 'one |  | two | three / a |  | b | c',
     tableRows().join(' / '));
  ok('and the strip is redrawn at the Run\'s new width, the Column carried along',
     strip() === '1one / 2 / 3two* / 4three', strip());
  key('z', document, false, true);
  ok('one ^Z takes back a strip operation, in every Line of the Run',
     tableRows().join(' / ') === kept, tableRows().join(' / '));

  table3();
  pick(2);
  op('del');
  ok('remove from the strip takes that Column out of every Line',
     tableRows().join(' / ') === 'one | three / a | c', tableRows().join(' / '));
  ok('and with the Column gone nothing is selected and nothing is offered',
     strip() === '1one / 2three' && ops() === '', strip() + ' :: ' + ops());
  key('z', document, false, true);
  ok('one ^Z takes back the removal in every Line',
     tableRows().join(' / ') === kept, tableRows().join(' / '));

  table3();
  pick(2);
  op('left');
  ok('move left swaps it with its neighbour, in every Line',
     tableRows().join(' / ') === 'two | one | three / b | a | c',
     tableRows().join(' / '));
  ok('and the selection follows the Column that moved',
     strip() === '1two* / 2one / 3three', strip());
  op('right');
  ok('move right puts it back, in every Line',
     tableRows().join(' / ') === kept, tableRows().join(' / '));
  ok('and the selection came back with it', strip() === '1one / 2two* / 3three', strip());

  /* a ragged Run: the first operation squares it, and the rows that were
     already the Run's width are rewritten to exactly what they said */
  document.getElementById('actClear').click();
  key('t');
  key('i');
  type('one | two');
  key('Escape', box());
  key('o');
  type('a | b | c');
  key('Escape', box());
  pick(3);
  op('left');
  ok('a ragged Run is padded to its width by the first operation',
     tableRows().join(' / ') === 'one |  | two / a | c | b', tableRows().join(' / '));

  /* the Run's bounds hold: a second Table is a Run of its own */
  document.getElementById('actClear').click();
  key('t');
  key('i');
  type('a1 | a2');
  key('Escape', box());
  key('o');
  key('Escape', box());
  key('p');
  key('i');
  type('between');
  key('Escape', box());
  key('o');
  key('Escape', box());
  key('t');
  key('i');
  type('b1 | b2');
  key('Escape', box());
  pick(1);
  op('add');
  ok('an operation stops at the Run the strip belongs to',
     tableRows().join(' / ') === 'a1 | a2 /  | b1 | b2', tableRows().join(' / '));

  /* a refusal is the operation's own sentence, and nothing happens */
  document.getElementById('actClear').click();
  key('t');
  key('i');
  type('only');
  key('Escape', box());
  pick(1);
  op('del');
  ok('remove on a Run one Column wide is refused, in the command\'s words',
     msg() === 'a table is at least one column wide', msg());
  ok('and the Line is exactly as it was',
     tableRows().join(' / ') === 'only', tableRows().join(' / '));

  table3();
  pick(1);
  op('left');
  ok('move left on Column 1 is refused',
     msg() === 'column 1 has no neighbour on the left', msg());
  ok('and nothing moved', tableRows().join(' / ') === kept, tableRows().join(' / '));
  pick(3);
  op('right');
  ok('move right on the last Column is refused the same way',
     msg() === 'column 3 has no neighbour on the right', msg());
  ok('and nothing moved there either',
     tableRows().join(' / ') === kept, tableRows().join(' / '));

  /* the same two operations, on the keyboard */
  table3();
  pick(3);
  key('ArrowLeft', document, false, true);
  ok('^← moves the selected Column left, in every Line',
     tableRows().join(' / ') === 'one | three | two / a | c | b',
     tableRows().join(' / '));
  key('ArrowRight', document, false, true);
  ok('^→ moves it back', tableRows().join(' / ') === kept, tableRows().join(' / '));
  ok('and the selection is still on it, drawn', strip() === '1one / 2two / 3three*', strip());

  /* out of the Run: a new line below the last row, made a Paragraph */
  key('o');
  key('Escape', box());
  key('p');
  ok('leaving the Run drops the selection', ops() === '' && strip() === '',
     ops() + ' :: ' + strip());
  var quiet = tableRows().join(' / ');
  key('ArrowLeft', document, false, true);
  ok('^← with nothing selected does nothing and changes nothing',
     tableRows().join(' / ') === quiet, tableRows().join(' / '));

  /* :col is unchanged and still the complete path — all four of it */
  table3();
  run('col right 1');
  ok(':col right still swaps a Column with the one after it',
     tableRows().join(' / ') === 'two | one | three / b | a | c',
     tableRows().join(' / '));
  run('col left 2');
  ok(':col left still puts it back', tableRows().join(' / ') === kept, tableRows().join(' / '));
  run('col add 1');
  ok(':col add still puts an empty Column where it is told',
     tableRows().join(' / ') === ' | one | two | three /  | a | b | c',
     tableRows().join(' / '));
  run('col del 1');
  ok(':col del still takes it out again', tableRows().join(' / ') === kept, tableRows().join(' / '));

  document.getElementById('actClear').click();
  key('c');
  key('Tab');
  ok('Tab outside the box still cycles the Dialect',
     msg() === 'js' && document.querySelector('#sheet .run.code .lang').textContent === 'js',
     msg() + ' :: ' + document.querySelector('#sheet .run.code .lang').textContent);

  /* --- the address overlay: the links in a line, and an image's two halves -- */
  function addrOn()  { return document.getElementById('addr').classList.contains('on'); }
  function picking() { return addrOn() && !document.getElementById('addrPick').hidden; }
  function fa()      { return document.getElementById('addrA'); }
  function fb()      { return document.getElementById('addrB'); }
  function warn()    { return document.getElementById('addrWarn').textContent; }
  /* a fresh document holding one line of the given text */
  function oneLine(text) {
    document.getElementById('actClear').click();
    key('i');
    type(text);
    key('Escape', box());
  }

  oneLine('see [one](https://a.example/) and [two](https://b.example/)');
  key('a');
  ok('a on a line with two links opens the picker', picking());
  ok('the picker offers both links and a new one',
     document.querySelectorAll('#addrPick b').length === 3,
     document.querySelectorAll('#addrPick b').length);
  key('2');
  ok('picking the second fills the form with the second link',
     fa().value === 'two' && fb().value === 'https://b.example/',
     fa().value + ' / ' + fb().value);
  key('Escape', fa());
  key('a');
  key('j');
  key('Enter');
  ok('j and Enter reach the same link the digit does',
     !picking() && fa().value === 'two' && fb().value === 'https://b.example/',
     fa().value + ' / ' + fb().value);
  key('Escape', fa());
  key('a');
  key('j');
  key('k');
  key('Enter');
  ok('k comes back up the list', fa().value === 'one', fa().value);
  key('Escape', fa());
  key('a');
  key('2');
  fa().focus();
  key('Tab', fa());
  ok('Tab moves to the other field', document.activeElement === fb(),
     document.activeElement && document.activeElement.id);
  fa().value = 'TWO';
  fb().value = 'https://c.example/';
  key('Enter', fb());
  ok('Enter commits and closes the overlay', !addrOn());
  ok('and the line carries the link that was typed',
     rows().join('|').indexOf('see [one](https://a.example/) and [TWO](https://c.example/)') > -1,
     rows().join('|'));

  var kept2 = rows().join('|');
  key('a');
  key('1');
  fa().value = 'thrown away';
  key('Escape', fa());
  ok('Esc leaves the line exactly as it was',
     !addrOn() && rows().join('|') === kept2, rows().join('|'));

  run('link');
  ok(': link opens the same overlay as a', addrOn());
  key('Escape', fa());
  run('img');
  ok(': img opens it too', addrOn());
  key('Escape', fa());

  oneLine('one [only](https://a.example/) here');
  key('a');
  ok('one link goes straight to a filled form',
     addrOn() && !picking() && fa().value === 'only', fa().value);
  key('Escape', fa());

  oneLine('no links here');
  key('a');
  ok('no links goes straight to an empty form',
     addrOn() && !picking() && !fa().value && !fb().value, fa().value + ' / ' + fb().value);
  fa().value = 'fresh';
  fb().value = 'https://d.example/';
  key('Enter', fa());
  ok('a new link is appended to the line',
     rows().join('|').indexOf('no links here [fresh](https://d.example/)') > -1, rows().join('|'));

  key('a');
  fb().value = '';
  key('Enter', fa());
  ok('an empty href unlinks and keeps the wording',
     rows().join('|').indexOf('no links here fresh') > -1 &&
     rows().join('|').indexOf('[fresh]') < 0, rows().join('|'));

  oneLine('a [word](https://a.example/) here');
  var before2 = rows().join('|');
  key('a');
  fa().value = '';
  key('Enter', fa());
  ok('an empty wording is refused, with a message and no change',
     addrOn() && msg().indexOf('wording') > -1 && rows().join('|') === before2,
     msg() + ' :: ' + rows().join('|'));

  fa().value = 'word';
  fb().value = 'javascript:alert';
  fb().dispatchEvent(new Event('input', { bubbles: true }));
  ok('an href the allowlist refuses is marked in the overlay',
     warn().indexOf('print as text') > -1, warn());
  key('Enter', fb());
  ok('and Enter commits it anyway',
     !addrOn() && rows().join('|').indexOf('[word](javascript:alert)') > -1, rows().join('|'));

  key('z', document, false, true);
  ok('one committed overlay is one ^Z',
     rows().join('|') === before2, rows().join('|'));

  document.getElementById('actClear').click();
  key('c');
  var kept3 = rows().join('|');
  key('a');
  ok('a on a code line says so and changes nothing',
     !addrOn() && msg().indexOf('nothing to address') > -1 && rows().join('|') === kept3,
     msg() + ' :: ' + rows().join('|'));

  /* the legend is the whole interface where there is no keyboard, so the
     address overlay has to be reachable from it and not from `a` alone */
  oneLine('[wording](https://a.example/)');
  var addrChip = document.querySelector('#legend b[data-a="addr"]');
  ok('the legend offers the address action', !!addrChip,
     document.querySelectorAll('#legend b[data-a]').length + ' actions');
  ok('and prints the key that does the same thing',
     !!addrChip && addrChip.querySelector('i').textContent === 'a',
     addrChip && addrChip.innerHTML);
  if (addrChip) { addrChip.click(); }
  ok('clicking it opens the overlay on the line under the cursor',
     addrOn() && !picking() && fa().value === 'wording', fa().value);
  key('Escape');

  document.getElementById('actClear').click();
  key('f');
  key('a');
  ok('a on an image line offers src and caption',
     addrOn() && document.getElementById('addrLab1').textContent === 'src' &&
     document.getElementById('addrLab2').textContent === 'caption',
     document.getElementById('addrLab1').textContent);
  fa().value = 'diagram.png';
  fb().value = 'how it fits together';
  key('Enter', fb());
  var md = exported();
  ok('a committed caption reaches the export',
     md.indexOf('![how it fits together](diagram.png)') > -1, md);
  var fig = document.querySelector('#read figure');
  ok('and the read pane shows the picture itself',
     !!document.querySelector('#read figure img[src="diagram.png"]'),
     fig && fig.innerHTML);
  ok('with the box holding the file name behind it, for an src that will not load',
     !!fig && !!fig.querySelector('.imgbox[hidden]') &&
     fig.querySelector('.imgbox').textContent === 'diagram.png',
     fig && fig.innerHTML);
  ok('and the caption is the alt as well as the figcaption',
     !!fig && fig.querySelector('img').alt === 'how it fits together' &&
     fig.querySelector('figcaption').textContent === 'how it fits together',
     fig && fig.innerHTML);

  /* the two halves are cut down to what `![caption](src)` can hold, as a
     link's are — otherwise the exported Line reads back as a Paragraph */
  key('a');
  fa().value = 'pic).png';
  fb().value = 'a cap]tion';
  key('Enter', fb());
  md = exported();
  ok('an src and a caption are cut down to what the syntax carries',
     md.indexOf('![a caption](pic.png)') > -1, md);

  oneLine('[kept  wording](https://a.example/)');
  key('a');
  fb().value = '';
  key('Enter', fa());
  ok('unlinking keeps the wording the field shows',
     rows().join('|').indexOf('kept  wording') > -1 &&
     rows().join('|').indexOf('[') < 0, rows().join('|'));

  oneLine('[old](https://a.example/)');
  key('a');
  fa().value = 'new wording';
  fb().value = '';
  key('Enter', fa());
  ok('and a wording edited on the way out is not thrown away',
     rows().join('|').indexOf('new wording') > -1, rows().join('|'));

  /* --- ^K: the link lands where the writer is ---------------------------- */
  /* The overlay reached from inside the box, with the offsets read off the box
     itself. `a` on a closed Line still appends — there is no caret in it. */
  function putSelection(at, end) {
    var b = box(), r = document.createRange(), s = getSelection();
    r.setStart(b.firstChild, at);
    r.setEnd(b.firstChild, end);
    s.removeAllRanges();
    s.addRange(r);
  }
  function ctrlK() { key('k', box(), false, true); }

  oneLine('take these words away');
  key('i');
  putSelection(5, 16);
  ctrlK();
  ok('^K with a selection opens the overlay with the selection as the wording',
     addrOn() && !picking() && fa().value === 'these words', fa().value);
  fb().value = 'https://w.example/';
  key('Enter', fb());
  var placed = rows().join('|');
  ok('committing replaces exactly the selected span, and the rest is untouched',
     placed.indexOf('take [these words](https://w.example/) away') > -1, placed);
  ok('the caret sits after the inserted link', caret() === 38, caret());
  document.execCommand('insertText', false, '!');
  ok('and typing carries on there',
     box() && box().textContent.indexOf(')! away') > -1, box() && box().textContent);
  key('Escape', box());

  oneLine('before after');
  key('i');
  putCaret(7);
  ctrlK();
  ok('^K with a caret and no selection opens an empty form',
     addrOn() && !picking() && !fa().value && !fb().value, fa().value + ' / ' + fb().value);
  fa().value = 'here';
  fb().value = 'https://h.example/';
  key('Enter', fb());
  ok('and the committed link lands at the caret',
     rows().join('|').indexOf('before [here](https://h.example/)after') > -1, rows().join('|'));
  key('Escape', box());
  key('z', document, false, true);
  ok('one insertion at the caret is one ^Z',
     rows().join('|').indexOf('before after') > -1 &&
     rows().join('|').indexOf('[here]') < 0, rows().join('|'));

  /* a line break in the box — Shift+Enter puts one there — commits as one
     character, so the offset read off the box is the offset in the Line */
  oneLine('ab');
  key('i');
  box().textContent = 'ab\n\ncd';
  putCaret(4);
  ctrlK();
  fa().value = 'w';
  fb().value = 'https://b.example/';
  key('Enter', fb());
  ok('a caret past two line breaks is still where the link lands',
     rows().join('|').indexOf('ab  [w](https://b.example/)cd') > -1, rows().join('|'));
  key('Escape', box());

  oneLine('leave me alone');
  var keptK = rows().join('|');
  key('i');
  putCaret(5);
  ctrlK();
  fa().value = 'never';
  fb().value = 'https://n.example/';
  key('Escape', fb());
  key('Escape', box());
  ok('Esc leaves the line exactly as it was',
     !addrOn() && rows().join('|') === keptK, rows().join('|'));

  oneLine('take these words away');
  key('i');
  putSelection(4, 16);
  ctrlK();
  ok('a selection that took a space with it links the phrase, not the space',
     fa().value === 'these words', fa().value);
  fb().value = 'https://w.example/';
  key('Enter', fb());
  ok('and the space it took is still there',
     rows().join('|').indexOf('take [these words](https://w.example/) away') > -1,
     rows().join('|'));
  key('Escape', box());
  key('z', document, false, true);
  ok('one link over a selection is one ^Z too',
     rows().join('|').indexOf('take these words away') > -1, rows().join('|'));

  oneLine('keep this exactly');
  key('i');
  putSelection(5, 9);
  ctrlK();
  key('Escape', fa());
  ok('Esc hands the selection back, not just the text',
     !addrOn() && !!box() && String(getSelection()) === 'this', String(getSelection()));
  key('Escape', box());

  document.getElementById('actClear').click();
  key('f');
  key('i');
  var keptF = rows().join('|');
  ctrlK();
  ok('^K on an image line offers nothing new and changes nothing',
     !addrOn() && msg().indexOf('src and caption') > -1 && rows().join('|') === keptF,
     msg() + ' :: ' + rows().join('|'));
  key('Escape', box());

  oneLine('see [one](https://a.example/) here');
  key('i');
  putCaret(29);
  ctrlK();
  fa().value = 'two';
  fb().value = 'https://b.example/';
  key('Enter', fb());
  key('Escape', box());
  ok('a line that already carried a link reports both afterwards, in order',
     window.TerminalCms.links(rows().join('|')).map(function (k) { return k.wording; })
       .join(' ') === 'one two',
     rows().join('|'));

  oneLine('tail text');
  key('a');
  fa().value = 'end';
  fb().value = 'https://e.example/';
  key('Enter', fb());
  ok('a on a line that is not being edited still appends',
     rows().join('|').indexOf('tail text [end](https://e.example/)') > -1, rows().join('|'));

  document.getElementById('actClear').click();
  key('c');
  key('i');
  var keptC = rows().join('|');
  ctrlK();
  ok('^K on a code line says so and changes nothing',
     !addrOn() && msg().indexOf('nothing to address') > -1 && rows().join('|') === keptC,
     msg() + ' :: ' + rows().join('|'));
  key('Escape', box());

  document.getElementById('actClear').click();
  key('t');
  key('i');
  type('a | b | c');
  putCaret(1);
  key('Tab', box());
  ok('Tab still walks Cells, unaffected by the new binding', caret() === 5, caret());
  key('Escape', box());


  /* --- markdown in by paste: ^V with no Line open ----------------------- */
  /* A synthetic paste carries a clipboard of its own, with HTML beside the
     text the way a copy from a web page does — only the text may arrive. The
     clipboard is a stand-in that shadows the event's own: a DataTransfer made
     in script reaches the listener as a copy, which Chromium fills and Firefox
     hands over empty, so the stand-in answers getData() as the real one would
     in either. The listeners under test read nothing else of it. */
  function paste(text, el) {
    var held = { 'text/plain': text, 'text/html': '<h1>not this</h1>' };
    var ev = new ClipboardEvent('paste', { bubbles: true, cancelable: true });
    Object.defineProperty(ev, 'clipboardData', {
      value: { getData: function (type) { return held[type] || ''; } }
    });
    (el || document.body).dispatchEvent(ev);
    return ev;
  }

  oneLine('above');
  key('o');
  type('below');
  key('Escape', box());
  key('k');
  run('title Before');
  var unpasted = rows().join('|');
  var ev = paste('---\ntitle: Pasted\nauthor: me\n---\n\n## A heading\n\n- an item\n\n' +
                 '```bash\necho hi\n```\n');
  ok('a paste with nothing open is taken by the Document', ev.defaultPrevented);
  ok('and its Lines land typed, below the cursor, with the cursor on the last',
     rows().join('|') === 'meta:title: Pasted|meta:author: me|p:above|h2:A heading|' +
       'list:an item|code*:echo hi|p:below', rows().join('|'));
  ok('the clipboard\'s HTML is not read', rows().join('|').indexOf('not this') < 0,
     rows().join('|'));
  ok('the status line says what the paste added and set',
     /3 lines/.test(msg()) && /2 meta/.test(msg()), msg());
  key('z', document, false, true);
  ok('one ^Z takes the whole paste back, Meta included',
     rows().join('|') === unpasted, rows().join('|'));
  key('z', document, true, true);
  ok('and ^⇧Z puts it all back', rows().join('|').indexOf('title: Pasted') > -1 &&
     rows().join('|').indexOf('echo hi') > -1, rows().join('|'));

  var kept4 = rows().join('|');
  paste(' \n\t\n');
  ok('a paste with nothing in it changes nothing and says so',
     rows().join('|') === kept4 && /nothing/.test(msg()), msg() + ' :: ' + rows().join('|'));

  /* what a paste brings in reaches the page as text wherever the page shows
     it — the status line included, which names an Image Line by its caption */
  paste('![<b>a caption</b> <img src=x onerror="document.body.dataset.ran=1">](x.png)\n');
  var right = document.getElementById('right');
  ok('a pasted caption reaches the status line as text, not as markup',
     rows().join('|').indexOf('img*:x.png') > -1 && !right.querySelector('*') &&
       right.textContent.indexOf('<b>a caption</b>') > -1,
     right.innerHTML);

  /* the in-edit paste is untouched: into an open Line it is text, and further
     lines are Lines of that Line's Type — a script's comment stays a comment */
  document.getElementById('actClear').click();
  key('c');
  run('lang bash');
  key('i');
  ev = paste('# a comment\necho two', box());
  ok('a paste into an open Code Line still gives Code Lines of that Dialect',
     rows().join('|') === 'code:# a comment|code*:echo two' &&
     [].map.call(document.querySelectorAll('#sheet .run.code .lang'),
       function (x) { return x.textContent; }).join() === 'bash',
     rows().join('|'));
  ok('and its # comment is not a heading', !document.querySelector('#sheet .ln.h1'),
     rows().join('|'));
  key('Escape', box());

  var kept5 = rows().join('|');
  var input2 = typeCmd('ti');
  ev = paste('## into the command line', input2);
  ok('a paste with the command line open goes to the command line',
     !ev.defaultPrevented && rows().join('|') === kept5, rows().join('|'));
  key('Escape', input2);

  key('?');
  ev = paste('## under the help');
  ok('a paste with an overlay open is left alone',
     !ev.defaultPrevented && rows().join('|') === kept5, rows().join('|'));
  key('Escape');

  key('R');
  ev = paste('## into the name', document.getElementById('docname'));
  ok('a paste into the Name goes to the Name',
     !ev.defaultPrevented && rows().join('|') === kept5, rows().join('|'));
  key('Escape', document.getElementById('docname'));

  /* the Name takes the focus from Tab without being open, and is still the
     Name: a paste there is not the Document's */
  document.getElementById('docname').focus();
  ev = paste('## at the focused name', document.getElementById('docname'));
  ok('a paste with the focus on the Name, not open, is left alone',
     !ev.defaultPrevented && rows().join('|') === kept5, rows().join('|'));
  document.getElementById('docname').blur();

  run('read');
  paste('- read face');
  ok('a paste with the read face showing adds at the cursor and keeps the face',
     rows().join('|').indexOf('list*:read face') > -1 &&
     document.getElementById('panes').dataset.mode === 'read', rows().join('|'));
  run('write');

  /* --- :paste and the Legend's paste: the Clipboard API ----------------- */
  var kept6;
  /* navigator.clipboard stood in for, answering at once, so the probe stays
     one synchronous run: a thenable is all the call site asks of it */
  function withClipboard(fake, fn) {
    var had = Object.getOwnPropertyDescriptor(navigator, 'clipboard');
    Object.defineProperty(navigator, 'clipboard', { value: fake, configurable: true });
    try { fn(); } finally {
      if (had) Object.defineProperty(navigator, 'clipboard', had);
      else delete navigator.clipboard;
    }
  }
  function holding(text) {
    return { readText: function () { return { then: function (yes) { yes(text); } }; } };
  }
  var refusing = {
    readText: function () { return { then: function (yes, no) { no(new Error('denied')); } }; }
  };

  var pasteChip = document.querySelector('#legend b[data-a="paste"]');
  ok('the legend offers paste', !!pasteChip,
     document.querySelectorAll('#legend b[data-a]').length + ' actions');
  ok('beside new', !!pasteChip && !!pasteChip.previousElementSibling &&
     pasteChip.previousElementSibling.dataset.a === 'new',
     pasteChip && pasteChip.previousElementSibling && pasteChip.previousElementSibling.outerHTML);
  ok('and prints ^V as the key that does the same thing',
     !!pasteChip && pasteChip.querySelector('i').textContent === '^V',
     pasteChip && pasteChip.innerHTML);

  document.getElementById('actClear').click();
  /* the legend is redrawn by every render(), so the chip is found again */
  pasteChip = document.querySelector('#legend b[data-a="paste"]');
  withClipboard(holding('- from the legend'), function () {
    if (pasteChip) pasteChip.click();
  });
  ok('clicking it reads the clipboard and adds what it holds',
     rows().join('|') === 'p:write…|list*:from the legend', rows().join('|'));
  withClipboard(holding('> from the command'), function () { run('paste'); });
  ok(':paste does the same', rows().join('|').indexOf('quote*:from the command') > -1,
     rows().join('|'));

  /* the clipboard answers late — after a permission prompt — and a Line the
     writer opened in the meantime is theirs, not the paste's */
  var answer = null;
  kept6 = rows().join('|');
  withClipboard({ readText: function () {
    return { then: function (yes) { answer = yes; } };
  } }, function () { run('paste'); });
  key('i');
  type('typed while waiting');
  if (answer) answer('## arrived late');
  ok('a clipboard that answers after a Line was opened pastes nothing and says so',
     !!box() && rows().join('|').indexOf('arrived late') < 0 && /nothing pasted/.test(msg()),
     msg() + ' :: ' + rows().join('|'));
  key('Escape', box());
  ok('and the open Line kept what was typed into it',
     rows().join('|').indexOf('typed while waiting') > -1, rows().join('|'));

  kept6 = rows().join('|');
  withClipboard(refusing, function () { run('paste'); });
  ok('a refused clipboard changes nothing and points at ^V',
     rows().join('|') === kept6 && /\^V/.test(msg()), msg() + ' :: ' + rows().join('|'));
  withClipboard({}, function () { run('paste'); });
  ok('so does a clipboard with no readText',
     rows().join('|') === kept6 && /\^V/.test(msg()), msg());
  withClipboard(undefined, function () { run('paste'); });
  ok('and one that is not there at all, as in an insecure context',
     rows().join('|') === kept6 && /\^V/.test(msg()), msg());

  ok('the help lists :paste among the commands',
     [].some.call(document.querySelectorAll('#cmdlist kbd'),
       function (k) { return k.textContent === 'paste'; }));
  ok('and ^V among the keys',
     [].some.call(document.querySelectorAll('#help kbd'),
       function (k) { return k.textContent === '^V'; }));

  /* --- the raw face: the Export bytes, live, and not a place to type ----- */
  var panesEl = document.getElementById('panes');
  var rawEl   = document.getElementById('raw');
  var readFace = document.getElementById('read');
  function mode() { return panesEl.dataset.mode; }
  function rawText() {
    var p = rawEl && rawEl.querySelector('pre');
    return p ? p.textContent : null;
  }
  function shown(el) { return !!el && el.getClientRects().length > 0; }
  function faceStored() {
    try { return localStorage.getItem('tcms-face'); } catch (e) { return 'unreadable'; }
  }

  document.getElementById('actClear').click();
  key('2');
  key('i');
  type('Raw face');
  key('Escape', box());
  key('o');
  type('with **bold** and a [link](https://example.com/)');
  key('Escape', box());
  key('p');

  key('w');
  ok('w shows raw', mode() === 'raw' && shown(rawEl) && !shown(readFace),
     mode() + ' raw ' + shown(rawEl) + ' read ' + shown(readFace));
  var rawMd = exported();
  ok('and its text is exactly what Export writes', rawText() === rawMd,
     JSON.stringify(rawText()) + ' vs ' + JSON.stringify(rawMd));
  ok('the markdown is the markdown, not the page', /\*\*bold\*\*/.test(rawText() || ''),
     rawText());
  ok('the legend is put away in raw, as in read', getComputedStyle(document.getElementById('legend')).display === 'none',
     getComputedStyle(document.getElementById('legend')).display);

  key('e');
  key('o');
  type('committed in write');
  key('Escape', box());
  key('w');
  ok('an edit committed in write changes raw',
     (rawText() || '').indexOf('committed in write') > -1 && rawText() === exported(),
     rawText());

  key('b');
  ok('split after w shows write and raw',
     mode() === 'split' && shown(document.getElementById('sheet')) && shown(rawEl) &&
     !shown(readFace), mode() + ' raw ' + shown(rawEl) + ' read ' + shown(readFace));
  ok('and remembers that split shows raw', faceStored() === 'raw', faceStored());
  key('o');
  type('typed beside raw');
  key('Enter', box());
  ok('raw follows a commit in split while the next Line is still open',
     (rawText() || '').indexOf('typed beside raw') > -1, rawText());
  key('Escape', box());
  key('B');
  ok('B still swaps the panes with raw beside write',
     panesEl.dataset.swap === 'yes' && mode() === 'split', panesEl.dataset.swap);
  key('B');

  key('v');
  key('b');
  ok('split after v shows write and read',
     mode() === 'split' && shown(readFace) && !shown(rawEl),
     mode() + ' raw ' + shown(rawEl) + ' read ' + shown(readFace));
  ok('and remembers that split shows read', faceStored() === 'read', faceStored());

  key('w');
  var rawBefore = rawText(), rowsBefore = rows().join('|');
  var rawPre = rawEl && rawEl.querySelector('pre');
  ok('raw is not editable', !!rawPre && !rawPre.isContentEditable && !rawEl.isContentEditable,
     rawPre && rawPre.contentEditable);
  if (rawPre) {
    var sel = window.getSelection();
    sel.removeAllRanges();
    var rng = document.createRange();
    rng.selectNodeContents(rawPre);
    sel.addRange(rng);
    /* a selection's text leaves out a <pre>'s last newline — the browser's
       doing, and the export overlay's copy is the byte-exact one */
    ok('its text can be selected, to be copied',
       sel.toString().replace(/\n$/, '') === rawBefore.replace(/\n$/, ''),
       JSON.stringify(sel.toString()));
    ['x', 'D', 'o', 'p', 'Enter', 'Backspace'].forEach(function (k) { key(k, rawPre); });
    document.execCommand('insertText', false, 'typed into raw');
    sel.removeAllRanges();
  }
  ok('typing in raw changes no Line',
     rows().join('|') === rowsBefore && rawText() === rawBefore && !box(),
     rows().join('|'));

  key('e');
  key('b', document, false, true);
  key('4');
  ok('^B 4 reaches raw', mode() === 'raw', mode());
  key('b', document, false, true);
  key('2');
  ok('^B 2 still reaches read', mode() === 'read', mode());
  run('raw');
  ok(':raw reaches raw', mode() === 'raw', mode());
  run('read');
  ok(':read reaches read', mode() === 'read', mode());

  var tabNames = [].map.call(document.querySelectorAll('.tabs [data-tab]'),
    function (b) { return b.dataset.tab; }).join(' ');
  ok('the tabs are write · read · raw · split', tabNames === 'write read raw split', tabNames);
  var rawTab = document.querySelector('.tabs [data-tab="raw"]');
  if (rawTab) rawTab.click();
  ok('and the raw tab shows raw, marked as the one on',
     mode() === 'raw' && !!rawTab && rawTab.classList.contains('on'), mode());
  var win = document.querySelector('.status [data-tab="raw"]');
  ok('the status bar lists raw as window 4, and marks it',
     !!win && win.textContent === '4:raw' && win.classList.contains('on'),
     win && win.outerHTML);

  var rawPasted = rows().length;
  paste('- pasted over raw');
  ok('a ^V paste with raw showing adds at the cursor',
     rows().length === rawPasted + 1 && rows().join('|').indexOf('list*:pasted over raw') > -1,
     rows().join('|'));
  ok('raw follows it',
     (rawText() || '').indexOf('- pasted over raw') > -1 && rawText() === exported(), rawText());
  ok('and the face stays raw', mode() === 'raw', mode());

  run('write');
  var expBtn = document.getElementById('actExport');
  ok('the top bar has Export .md, after New .md',
     !!expBtn && expBtn.textContent === 'Export .md' &&
     expBtn.previousElementSibling && expBtn.previousElementSibling.id === 'actNew',
     expBtn && expBtn.outerHTML);
  ok('and its title names E', !!expBtn && /\(E\)/.test(expBtn.title), expBtn && expBtn.title);
  if (expBtn) expBtn.click();
  ok('the Export .md button opens the export overlay',
     document.getElementById('exp').classList.contains('on') &&
     document.getElementById('expMd').textContent === rawText(),
     document.getElementById('exp').className);
  key('Escape');

  var helpText = document.getElementById('help').textContent;
  ok('the help lists w and ^B 4', [].some.call(document.querySelectorAll('#help kbd'),
       function (k) { return /(^| )w( |$)/.test(k.textContent) && /\^B 4/.test(k.textContent); }),
     helpText.length);
  ok('and Export .md beside New .md', [].some.call(document.querySelectorAll('#help kbd'),
       function (k) { return /^Export \.md/.test(k.textContent); }));
  ok('and :raw among the commands', [].some.call(document.querySelectorAll('#cmdlist kbd'),
       function (k) { return k.textContent === 'raw'; }));

  /* leave split showing read, as a fresh Editor would */
  run('read');
  run('write');

  /* --- the Palette: T flips it, and the Editor keeps it ---------------- */
  var htmlEl = document.documentElement;
  ok('it opened in the Theme it kept, and in Baseline when it kept none or one it has not got',
     themeAtLoad === (THEME_NAMES.indexOf(themeKept) > -1 ? themeKept : 'baseline'),
     themeAtLoad + ' with ' + themeKept + ' kept');
  /* the colours below are Baseline's, so the Palette is flipped in it */
  run('theme baseline');
  ok('it opened in the Palette it kept, and in none when it kept none, so a fresh one follows the browser',
     paletteAtLoad === (paletteKept === 'light' || paletteKept === 'dark' ? paletteKept : null),
     paletteAtLoad + ' with ' + paletteKept + ' kept');
  var PAPER = { light: 'rgb(255, 255, 255)', dark: 'rgb(30, 30, 30)' };   /* Baseline's --bg */
  key('T');
  var flipped = htmlEl.getAttribute('data-palette');
  ok('T sets data-palette to light or dark, and says which',
     (flipped === 'light' || flipped === 'dark') && msg() === 'palette ' + flipped,
     flipped + ' / ' + msg());
  ok('and keeps it, which is what a reload opens in', paletteStored() === flipped, paletteStored());
  ok('and the page is drawn in it', getComputedStyle(document.body).backgroundColor === PAPER[flipped],
     getComputedStyle(document.body).backgroundColor);
  key('T');
  var back = htmlEl.getAttribute('data-palette');
  ok('T again flips it to the other, and keeps that',
     back === (flipped === 'dark' ? 'light' : 'dark') && paletteStored() === back &&
     getComputedStyle(document.body).backgroundColor === PAPER[back],
     back + ' kept ' + paletteStored());
  run('palette');
  ok(':palette flips it the same way', htmlEl.getAttribute('data-palette') === flipped &&
     msg() === 'palette ' + flipped, htmlEl.getAttribute('data-palette') + ' / ' + msg());
  run('palette');
  var paletteBtn = document.getElementById('palette');
  if (paletteBtn) paletteBtn.click();
  ok('the light/dark button in the top bar flips it too',
     !!paletteBtn && paletteBtn.textContent === 'light/dark' &&
     htmlEl.getAttribute('data-palette') === flipped && msg() === 'palette ' + flipped,
     (paletteBtn && paletteBtn.textContent) + ' / ' + htmlEl.getAttribute('data-palette'));
  if (paletteBtn) paletteBtn.click();
  /* and leave the profile keeping what it kept, so a fresh one stays fresh */
  try {
    if (paletteKept === null) localStorage.removeItem('tcms-palette');
    else localStorage.setItem('tcms-palette', paletteKept);
  } catch (e) {}
  if (paletteAtLoad === null) htmlEl.removeAttribute('data-palette');
  else htmlEl.setAttribute('data-palette', paletteAtLoad);

  /* --- the write pane has the read pane's measure ---------------------- */
  /* The two panes have different font bases — the sheet is 14px, the reader
     page is --global-font-size — so the same measure cannot be reached by
     copying a declaration in em. What is compared here is the number of
     pixels each pane ends up with. */
  var sheetEl = document.getElementById('sheet');
  var readEl  = document.getElementById('read');
  /* the cap the surface is under, the width it took, and the room it had: the
     pane's own inside, which is what a centred surface is centred in */
  function measure(el) { return parseFloat(getComputedStyle(el).maxWidth); }
  function width(el)   { return el.getBoundingClientRect().width; }
  function roomFor(el) { return el.parentNode.clientWidth; }
  function insideOf(el) {
    var pane = el.parentNode;
    return pane.getBoundingClientRect().left + pane.clientLeft;
  }

  run('read');
  var readCap = measure(readEl), readW = width(readEl), readRoom = roomFor(readEl);
  run('write');
  var writeCap = measure(sheetEl), writeW = width(sheetEl), writeRoom = roomFor(sheetEl);

  ok('in write mode the write surface takes the read pane\'s measure',
     Math.abs(writeCap - readCap) <= 1, writeCap + ' vs ' + readCap);
  ok('and where the window has room for it, the two panes are as wide as each other',
     readRoom <= readCap || writeRoom <= writeCap || Math.abs(writeW - readW) <= 1,
     writeW + ' vs ' + readW);

  run('read');
  var readCapAgain = measure(readEl);
  run('write');
  ok('write → read → write leaves the measure the same in both',
     measure(sheetEl) === writeCap && readCapAgain === readCap,
     measure(sheetEl) + '/' + writeCap + ' :: ' + readCapAgain + '/' + readCap);

  /* a cap that is a number is not yet a cap that binds: given a window with
     room to spare, the surface has to stop short of the pane it sits in */
  ok('the write surface is still capped — a wide window does not uncap the line',
     getComputedStyle(sheetEl).maxWidth !== 'none' && isFinite(writeCap) && writeCap > 0 &&
     (writeRoom <= writeCap || writeW < writeRoom),
     getComputedStyle(sheetEl).maxWidth + ' in ' + writeRoom);

  var inside = insideOf(sheetEl), sheetBox = sheetEl.getBoundingClientRect();
  ok('the write surface is still centred in its pane',
     Math.abs((sheetBox.left - inside) -
              (inside + roomFor(sheetEl) - sheetBox.right)) <= 1,
     (sheetBox.left - inside) + ' / ' + (inside + roomFor(sheetEl) - sheetBox.right));

  key('+');
  key('+');
  var writeBig = measure(sheetEl);
  run('read');
  var readBig = measure(readEl);
  run('write');
  ok('+ scales the content and the measure follows it, in both panes',
     Math.abs(writeBig - writeCap * 1.2) <= 1 && Math.abs(writeBig - readBig) <= 1,
     writeBig + ' vs ' + writeCap * 1.2 + ' :: ' + readBig);
  key('-');
  key('-');
  ok('- brings the measure back with the content',
     Math.abs(measure(sheetEl) - writeCap) <= 1, measure(sheetEl));
  key('0');

  run('split');
  var writePane = document.getElementById('tab-write').getBoundingClientRect();
  var readPane  = document.getElementById('tab-read').getBoundingClientRect();
  ok('split is unchanged: each pane fills its half, sheet and all',
     Math.abs(writePane.width - readPane.width) <= 1 &&
     getComputedStyle(sheetEl).maxWidth === 'none',
     writePane.width + ' vs ' + readPane.width + ' :: ' + getComputedStyle(sheetEl).maxWidth);
  run('write');

  /* --- the top bar and the tabs fit the window ------------------------- */
  /* body hides its overflow, so a control past the window's edge is one no
     pointer can reach. Holds at any width; open the probe at a phone's
     to make it bite. */
  var winW = document.documentElement.clientWidth;
  var pastEdge = [].filter.call(
    document.querySelectorAll('.topbar button, .topbar select, .tabs button, .tabs .doc'),
    function (el) {
      var r = el.getBoundingClientRect();
      return r.width && (r.left < -0.5 || r.right > winW + 0.5);
    }).map(function (el) { return el.id || el.textContent.trim(); });
  ok('every control in the top bar and the tabs is inside the window',
     pastEdge.length === 0, pastEdge.join(' ') + ' past ' + winW + 'px');

  /* --- the Theme: the menu, :theme, and the pane a Document pins ------- */
  /* a colour an element's custom property names, as getComputedStyle spells
     a colour — <html>'s unless another element is asked */
  function colourOf(prop, el) {
    var probe = document.createElement('i');
    probe.style.color = getComputedStyle(el || document.documentElement).getPropertyValue(prop).trim();
    document.body.appendChild(probe);
    var c = getComputedStyle(probe).color;
    probe.remove();
    return c;
  }
  var themeSel = document.getElementById('theme');
  ok('the top bar has a Theme menu after Clear, one entry per Theme, by label',
     !!themeSel && themeSel.previousElementSibling.id === 'actClear' &&
     themeSel.options.length === THEME_NAMES.length &&
     window.THEMES.every(function (t, i) {
       return themeSel.options[i].value === t.name && themeSel.options[i].textContent === t.label;
     }), themeSel && themeSel.options.length);
  ok('and it shows the Theme the Editor is in', !!themeSel && themeSel.value === 'baseline',
     themeSel && themeSel.value);
  var baselineBg = colourOf('--bg');
  function choose(name) {
    themeSel.value = name;
    themeSel.dispatchEvent(new Event('change', { bubbles: true }));
  }
  /* Retroma, because its paper is not Baseline's white in either Palette */
  choose('retroma');
  ok('the Editor is drawn in the Theme the menu chooses',
     getComputedStyle(document.body).backgroundColor === colourOf('--bg') && colourOf('--bg') !== baselineBg,
     getComputedStyle(document.body).backgroundColor + ' vs ' + baselineBg);
  choose('things');
  ok('choosing Things sets data-theme on <html>, keeps it, and says so',
     htmlEl.getAttribute('data-theme') === 'things' && themeStored() === 'things' &&
     msg() === 'theme things', htmlEl.getAttribute('data-theme') + ' kept ' + themeStored() + ' / ' + msg());
  ok('and the menu gives the keys back', document.activeElement !== themeSel);
  run('theme');
  ok(':theme alone says which Theme it is', msg() === 'theme things', msg());
  run('theme nope');
  ok(':theme refuses a name it has not got, and lists the ones it has',
     htmlEl.getAttribute('data-theme') === 'things' && /^no Theme "nope" — /.test(msg()) &&
     msg().indexOf(THEME_NAMES.join(' ')) > -1, msg());
  run('theme wasp');
  ok(':theme <name> sets it as the menu does, and the menu follows',
     htmlEl.getAttribute('data-theme') === 'wasp' && themeStored() === 'wasp' &&
     themeSel.value === 'wasp' && msg() === 'theme wasp', themeSel.value + ' / ' + msg());
  run('theme things');
  run('palette dark');
  ok(':palette dark sets it', htmlEl.getAttribute('data-palette') === 'dark' &&
     paletteStored() === 'dark' && msg() === 'palette dark', msg());
  run('palette light');
  ok(':palette light sets it', htmlEl.getAttribute('data-palette') === 'light' &&
     msg() === 'palette light', msg());
  run('palette tuesday');
  ok(':palette refuses another word and leaves it', htmlEl.getAttribute('data-palette') === 'light' &&
     msg() === 'palette light · dark', msg());
  var helpCmds = document.getElementById('cmdlist').textContent;
  ok('the ? overlay lists :theme and :palette',
     helpCmds.indexOf('theme [name]') > -1 && helpCmds.indexOf('palette [light|dark]') > -1, helpCmds);
  ok('and its T row says it is the palette',
     [].some.call(document.querySelectorAll('#help .row'), function (r) {
       return r.querySelector('kbd').textContent === 'T' &&
         r.querySelector('span').textContent === 'palette, light ⇄ dark';
     }));

  run('palette dark');
  document.getElementById('actClear').click();
  paste('---\ntheme: wasp\n---\n\n# Pinned\n');
  ok('a Document that pins wasp puts it on the read pane, and <html> keeps the writer\'s',
     readEl.getAttribute('data-theme') === 'wasp' && htmlEl.getAttribute('data-theme') === 'things',
     readEl.getAttribute('data-theme') + ' / ' + htmlEl.getAttribute('data-theme'));
  ok('with a copy of the Palette', readEl.getAttribute('data-palette') === 'dark',
     readEl.getAttribute('data-palette'));
  ok('and the pane is drawn in Wasp, dark',
     colourOf('--bg', readEl) !== colourOf('--bg') &&
     getComputedStyle(readEl).backgroundColor === colourOf('--bg', readEl),
     getComputedStyle(readEl).backgroundColor + ' / ' + colourOf('--bg', readEl));
  var waspDark = colourOf('--bg', readEl);
  key('T');
  ok('T flips the pane\'s copy with <html>',
     readEl.getAttribute('data-palette') === 'light' && colourOf('--bg', readEl) !== waspDark,
     readEl.getAttribute('data-palette'));
  ok('the raw face is not pinned', !document.getElementById('raw').hasAttribute('data-theme'));
  key('g');
  ok('the pin is the first Line', doc0() === 'meta:theme: wasp', doc0());
  key('Tab');
  var after = THEME_NAMES[(THEME_NAMES.indexOf('wasp') + 1) % THEME_NAMES.length];
  ok('Tab on theme: steps to the next Theme, wrapping, and the pane follows',
     doc0() === 'meta:theme: ' + after && readEl.getAttribute('data-theme') === after &&
     msg() === 'theme: ' + after, doc0() + ' / ' + readEl.getAttribute('data-theme'));
  key('Tab', document, true);
  ok('⇧Tab steps back', doc0() === 'meta:theme: wasp', doc0());
  key('D');
  ok('removing the pin puts the pane back in the writer\'s Theme',
     !readEl.hasAttribute('data-theme') && !readEl.hasAttribute('data-palette') &&
     colourOf('--bg', readEl) === colourOf('--bg'), readEl.getAttribute('data-theme'));
  key('z', document, false, true);
  key('g');
  key('i');
  type('theme: nope');
  key('Escape', box());
  ok('a misspelled pin leaves the pane in the writer\'s',
     doc0() === 'meta:theme: nope' && !readEl.hasAttribute('data-theme'), doc0());
  key('Tab');
  ok('and Tab on it starts the list', doc0() === 'meta:theme: ' + THEME_NAMES[0], doc0());
  paste('---\npalette: light\n---\n');
  key('g');
  key('j');
  key('Tab');
  ok('Tab on palette: steps to dark', rows()[1] === 'meta*:palette: dark', rows()[1]);
  ok('and palette: is not printed under the title',
     readEl.querySelector('.doc-meta').textContent.indexOf('palette') < 0,
     readEl.querySelector('.doc-meta').textContent);
  document.getElementById('actClear').click();
  /* back to Baseline in the Palette it was, keeping what the profile kept */
  run('theme baseline');
  try {
    if (themeKept === null) localStorage.removeItem('tcms-theme');
    else localStorage.setItem('tcms-theme', themeKept);
    if (paletteKept === null) localStorage.removeItem('tcms-palette');
    else localStorage.setItem('tcms-palette', paletteKept);
  } catch (e) {}
  if (paletteAtLoad === null) htmlEl.removeAttribute('data-palette');
  else htmlEl.setAttribute('data-palette', paletteAtLoad);
  function doc0() { return rows()[0].replace('*', ''); }


  /* --- a Diagram in the read pane -------------------------------------- */
  /* Drawing is asynchronous — the library arrives by a <script> and draws
     behind a promise — so from here the run waits on what it is looking for,
     each step starting when the last one has seen it or given up, and the
     report is printed at the end of the chain. */
  function until(cond, then) {
    var t0 = Date.now();
    (function poll() {
      var v = false;
      try { v = !!cond(); } catch (e) {}
      if (v || Date.now() - t0 > 15000) then(v); else setTimeout(poll, 25);
    })();
  }
  function library() { return document.querySelectorAll('script[src$="mermaid.min.js"]'); }
  function drawing() { return readEl.querySelector('.block > svg'); }
  function shape(svg, node) {
    return svg && svg.querySelector('[id*="flowchart-' + node + '-"] :is(rect, polygon, path)');
  }
  function fill(svg, node) { var s = shape(svg, node); return s ? getComputedStyle(s).fill : ''; }

  ok('a Document without a Diagram loads no script, through every redraw above',
     library().length === 0 && !window.mermaid, library().length + ' ' + typeof window.mermaid);

  var DIAGRAM = 'graph TD\n  A[Start] --> B{Is it?}\n  B -->|Yes| C[Done]\n  style C fill:#f9f';
  /* every style attribute the read pane is given, and what it was before */
  var styled = [];
  var watch = new MutationObserver(function (rs) { styled = styled.concat(rs); });
  watch.observe(readEl, { subtree: true, attributes: true, attributeFilter: ['style'],
                          attributeOldValue: true });

  /* what the body holds before anything is drawn: the library draws in a
     scratch element of its own, which has to be gone again afterwards */
  function bodyNow() {
    return [].map.call(document.body.children, function (e) {
      return e.nodeName.toLowerCase() + (e.id ? '#' + e.id : '');
    }).join(' ');
  }
  var bodyThen = bodyNow();

  run('read');
  document.getElementById('actClear').click();
  paste('```mermaid\n' + DIAGRAM + '\n```\n\n```bash\necho plain\n```\n');
  ok('the first redraw that finds a Diagram adds one <script> for the library',
     library().length === 1, library().length);
  ok('and asks for the Editor\'s own copy, from beside the page\'s script',
     library().length === 1 && /\/editor\/mermaid\.min\.js$/.test(library()[0].src),
     library()[0] && library()[0].src);

  until(drawing, function () {
    var svg = drawing(), block = svg && svg.closest('.block');
    ok('a Diagram in the read pane becomes an <svg>', !!svg, readEl.innerHTML.slice(0, 200));
    ok('which takes the place of the <pre>',
       !!block && !block.querySelector('pre') &&
       block.querySelector('.block-bar .lang').textContent === 'mermaid',
       block && block.innerHTML.slice(0, 200));
    ok('and an ordinary code block beside it stays a code block',
       [].some.call(readEl.querySelectorAll('.block pre.code'),
                    function (p) { return p.textContent === 'echo plain'; }),
       readEl.querySelectorAll('pre.code').length);

    /* a <style> is what the page's policy refuses: the drawing's stylesheet
       is one the document adopts, which no style-src governs */
    ok('the SVG carries no <style> element',
       !!svg && !svg.querySelector('style') && !document.querySelector('style'),
       svg && svg.querySelectorAll('style').length);
    var bg = colourOf('--bg'), a = fill(svg, 'A');
    ok('a node\'s fill is the page\'s background, read from its custom properties',
       a === bg, a + ' vs ' + bg);
    var adopted = document.adoptedStyleSheets.slice();
    var mine = adopted.filter(function (sh) {
      return [].some.call(sh.cssRules, function (r) {
        return svg && r.selectorText && r.selectorText.indexOf('#' + svg.id) > -1;
      });
    });
    ok('the drawing\'s stylesheet is one the document adopted', mine.length === 1,
       mine.length + ' of ' + adopted.length);
    if (mine.length === 1) {
      document.adoptedStyleSheets = adopted.filter(function (sh) { return sh !== mine[0]; });
      var bare = fill(svg, 'A');
      document.adoptedStyleSheets = adopted;
      ok('and it comes from the placed stylesheet — without it the fill is not that',
         bare !== a && fill(svg, 'A') === a, bare + ' / ' + fill(svg, 'A'));
    }
    ok('a style statement in the source still colours its node',
       fill(svg, 'C') === 'rgb(255, 153, 255)', fill(svg, 'C'));

    /* A style attribute in markup is what the policy refuses. What the
       placement may leave is one it wrote through the CSSOM once the SVG was
       in the page, a declaration at a time — seen here as each element's
       first change starting from no attribute at all. */
    var inSvg = styled.filter(function (r) { return svg && svg.contains(r.target); });
    var firsts = inSvg.filter(function (r, i) {
      return !inSvg.slice(0, i).some(function (q) { return q.target === r.target; });
    });
    var carried = svg ? [svg].concat([].slice.call(svg.querySelectorAll('*')))
      .filter(function (el) { return el.hasAttribute('style'); }) : [];
    ok('no element in the placed SVG has a style attribute it arrived with',
       carried.length > 0 && firsts.every(function (r) { return r.oldValue === null; }) &&
       carried.every(function (el) {
         return inSvg.some(function (r) { return r.target === el; });
       }),
       carried.length + ' styled, ' + firsts.length + ' written, ' +
       firsts.filter(function (r) { return r.oldValue !== null; }).length + ' had one before');
    watch.disconnect();

    key('k');
    ok('a redraw puts the drawing straight back, with no flash of source',
       !!drawing() && ![].some.call(readEl.querySelectorAll('pre.code'),
                     function (p) { return /graph TD/.test(p.textContent); }),
       readEl.querySelectorAll('pre.code').length + ' pre');

    var copied = null;
    withClipboard({ writeText: function (s) { copied = s; return { then: function () {} }; } },
      function () {
        var b = drawing() && drawing().closest('.block').querySelector('button.copy');
        if (b) b.click();
      });
    ok('the copy button on a Diagram copies its source', copied === DIAGRAM,
       JSON.stringify(copied));

    var dark = fill(drawing(), 'A');
    key('T');
    until(function () { return fill(drawing(), 'A') !== dark; }, function () {
      ok('T redraws the Diagram, and its fill follows the theme',
         fill(drawing(), 'A') !== dark && fill(drawing(), 'A') === colourOf('--bg'),
         dark + ' -> ' + fill(drawing(), 'A') + ' vs ' + colourOf('--bg'));
      key('T');
      until(function () { return fill(drawing(), 'A') === dark; }, function (back) {
        ok('and T again draws it as it was', back, fill(drawing(), 'A') + ' vs ' + dark);
        themed();
      });
    });
  });

  /* a Theme change redraws as a Palette flip does, in the Theme the pane is
     in: the writer's from the menu, the Document's from a theme: Meta Line */
  function themed() {
    var was = fill(drawing(), 'A');
    choose('retroma');
    until(function () { return fill(drawing(), 'A') && fill(drawing(), 'A') !== was; }, function () {
      ok('a Theme from the menu redraws the Diagram, in a fill from the new Theme',
         fill(drawing(), 'A') !== was && fill(drawing(), 'A') === colourOf('--bg'),
         was + ' -> ' + fill(drawing(), 'A') + ' vs ' + colourOf('--bg'));
      var inRetroma = fill(drawing(), 'A');
      paste('---\ntheme: wasp\n---\n');
      until(function () { return fill(drawing(), 'A') && fill(drawing(), 'A') !== inRetroma; }, function () {
        ok('and a theme: Meta Line redraws it in the pinned Theme\'s fill',
           fill(drawing(), 'A') === colourOf('--bg', readEl) && colourOf('--bg', readEl) !== inRetroma,
           inRetroma + ' -> ' + fill(drawing(), 'A') + ' vs ' + colourOf('--bg', readEl));
        choose('baseline');
        try {
          if (themeKept === null) localStorage.removeItem('tcms-theme');
          else localStorage.setItem('tcms-theme', themeKept);
          if (paletteKept === null) localStorage.removeItem('tcms-palette');
          else localStorage.setItem('tcms-palette', paletteKept);
        } catch (e) {}
        broken();
      });
    });
  }

  function broken() {
    document.getElementById('actClear').click();
    paste('```mermaid\ngraph TD\n  A --> --> (\n```\n');
    until(function () { return readEl.querySelector('.derr'); }, function () {
      var err = readEl.querySelector('.derr'), block = err && err.closest('.block');
      var pre = block && block.querySelector('pre.code');
      ok('an invalid Diagram keeps its code block', !!pre && !block.querySelector('svg'),
         block && block.innerHTML.slice(0, 200));
      ok('and shows Mermaid\'s message under it',
         !!pre && pre.nextElementSibling === err && /\S/.test(err.textContent),
         err && err.textContent);
      ok('and the page is left as it was — nothing of either drawing stays behind',
         bodyNow() === bodyThen, bodyThen + '\n  now ' + bodyNow());
      key('k');
      ok('a redraw prints the message once, not once more',
         readEl.querySelectorAll('.derr').length === 1, readEl.querySelectorAll('.derr').length);
      many();
    });
  }

  /* every redraw of a changed source or in another Theme is a new drawing,
     and the stylesheets go with the drawings the Editor keeps, not with
     every one it ever made */
  function many() {
    document.getElementById('actClear').click();
    var n = 0, last = '';
    (function next() {
      if (n === 40) {
        until(function () { return drawing() && drawing().textContent.indexOf(last) > -1; }, function (seen) {
          var kept = document.adoptedStyleSheets.length;
          ok('forty redrawn sources leave no more adopted stylesheets than drawings kept',
             seen && kept > 0 && kept <= 32, kept);
          themes(0);
        });
        return;
      }
      last = 'N' + (++n);
      document.getElementById('actClear').click();
      paste('```mermaid\ngraph TD\n  A[' + last + '] --> B\n```\n');
      until(function () { return drawing() && drawing().textContent.indexOf(last) > -1; }, next);
    })();
  }

  function themes(i) {
    if (i === THEME_NAMES.length * 3) {
      choose('baseline');
      var kept = document.adoptedStyleSheets.length;
      ok('and so does switching Themes, time after time',
         kept > 0 && kept <= 32, kept);
      missing();
      return;
    }
    var was = drawing() && drawing().id, name = THEME_NAMES[i % THEME_NAMES.length];
    if (name === document.documentElement.getAttribute('data-theme')) return themes(i + 1);
    choose(name);
    until(function () { return drawing() && drawing().id !== was; }, function () { themes(i + 1); });
  }

  /* an src that does not load falls back to the box with its file name */
  function missing() {
    document.getElementById('actClear').click();
    paste('![nothing there](no-such-picture.png)\n');
    function fig() { return readEl.querySelector('figure'); }
    until(function () { return fig() && fig().querySelector('img').hidden; }, function () {
      var f = fig(), img = f && f.querySelector('img'), b = f && f.querySelector('.imgbox');
      ok('an image whose src does not load shows the box with its file name',
         !!b && !b.hidden && b.textContent === 'no-such-picture.png', f && f.innerHTML);
      ok('and the picture is hidden', !!img && img.hidden, f && f.innerHTML);
      document.getElementById('actClear').click();
      run('write');
      finish();
    });
  }

  function finish() {
    /* Mermaid's measuring pass writes style attributes the policy refuses,
       and Chromium reports each; nothing else may be refused */
    var wrong = (window.PROBE_REFUSED || ['the watcher did not load']).filter(function (d) { return !/^style-src-attr$/.test(d); });
    ok('the run is refused no script and no stylesheet by the page\'s policy',
       wrong.length === 0, wrong.slice(0, 5).join(', ') + ' (' + wrong.length + ')');

    /* A page with no policy refuses nothing either, so the policy is asked
       once for what it is there to refuse: a handler written into the page
       as markup, which is what an escaping miss would write. It does not
       run, and the watcher hears why. */
    var heard = (window.PROBE_REFUSED || []).length;
    var held = document.createElement('div');
    held.innerHTML = '<button type="button" onclick="document.body.dataset.policy=\'off\'">x</button>';
    document.body.appendChild(held);
    held.firstChild.click();
    until(function () {
      return (window.PROBE_REFUSED || []).slice(heard).some(function (d) { return /^script-src/.test(d); });
    }, function (refused) {
      ok('and the policy is in force: a handler written as markup does not run, and is refused by name',
         refused && document.body.dataset.policy !== 'off',
         (refused ? 'refused' : 'not refused') + ', ' + (document.body.dataset.policy === 'off' ? 'ran' : 'did not run'));
      held.remove();
      delete document.body.dataset.policy;
      report();
    });
  }

  function report() {
    var bad = out.filter(function (l) { return l.indexOf('FAIL') === 0; }).length;
    var pre = document.createElement('pre');
    pre.style.cssText = 'position:fixed;inset:0;z-index:999;background:#111;color:#ddd;' +
      'font:12px/1.5 monospace;padding:14px;margin:0;overflow:auto;white-space:pre-wrap';
    pre.textContent = out.join('\n') + '\n\n' + bad + ' failed of ' + out.length;
    document.body.appendChild(pre);
    document.title = 'probe done';
  }
})();
